BEGIN TRANSACTION;
CREATE TABLE libs (
	id INTEGER NOT NULL,
	user_id INTEGER,
	readme TEXT,
	lib TEXT,
	title VARCHAR(128),
	description TEXT,
	version VARCHAR(32),
	license VARCHAR(128),
	tags TEXT,
    date DATETIME,
    shasum VARCHAR(40),
	PRIMARY KEY (id)
);
INSERT INTO `libs` VALUES (1,1,'# controller\n\nRead from the game controllers\n\n## Explanation\n\nThe keypress state of the NES controllers are read in serially, bit-by-bit, using a shift register.\n\nThe shift register must be latched (brought high and then low) by writing to $4016, and then reading from $4016 for controller 1 and $4017 for controller 2.\n\nThis library reads that data into a single variable for `controller1` and `controller2`.\n\n## Variables\n\n1 byte in the zeropage should be assigned to `controller1`\nOptionally, an additional byte in the zeropage should be assigned to `controller2`\n\nTo set the number of controllers to read, define the `CONTROLLER_COUNT` constant as 1 or 2\n\n## Methods\n\n`controller1_read` - Read controller 1\n`controller2_read` - Read controller 2\n\n## Example\n\n```\nCONTROLLER_COUNT = 2\n\n;;;;;;;;\n\n.rsset $0000\n\ncontroller1 .rs 1\ncontroller2 .rs 1\n\n;;;;;;;;\n\n.include <controller.asm>\n\n;;;;;;;;\n\n    JSR controller1_read\n\n    LDA <controller1\n    LDA <controller2\n```\n\n','.ifndef CONTROLLER_COUNT ; 1 controller by default\nCONTROLLER_COUNT = 1\n.endif\n\n    JMP controller_guard\n\n.if CONTROLLER_COUNT >= 1 ; if 1 or more controllers\n\n.ifndef controller1\n    .out "Please reserve 1 byte in the zeropage for a `controller1` variable"\n.endif\n\ncontroller1_read:\n    ; latch controller\n    LDA #$01\n    STA $4016\n    LDA #$00\n    STA $4016\n\n    LDX #$08\ncontroller1_loop:\n    LDA $4016        ; read controller 1 keypress\n    LSR A            ; shift keypress into carry\n    ROL <controller1 ; rotate carry into controller1\n    DEX\n    BNE controller1_loop ; loop through the rest of the buttons\n\n    RTS\n\n.endif\n\n;;;;;;;;\n\n.if CONTROLLER_COUNT == 2 ; if 2 controllers\n\n.ifndef controller2\n    .out "Please reserve 1 byte in the zeropage for a `controller2` variable"\n.endif\n\ncontroller2_read:\n    ; latch controller\n    LDA #$01\n    STA $4016\n    LDA #$00\n    STA $4016\n\n    LDX #$08\ncontroller2_loop:\n    LDA $4017        ; read controller 2 keypress\n    LSR A            ; shift keypress into carry\n    ROL <controller2 ; rotate carry into controller2\n    DEX\n    BNE controller2_loop ; loop through the rest of the buttons\n\n    RTS\n\n.endif\n\ncontroller_guard:\n\n','controller','Read from the game controllers','1.0.1','GPLv3','controller,keypad,controls,input','2017-05-06 12:00:00','0435ce066e6cc59d97d6edddadbd539cff1c538a');
INSERT INTO `libs` VALUES (2,1,'# prng\n\nPseudo-random number generator\n\n## Explanation\n\nThis library utilizes a linear feedback shift register to generate a 16-bit pseudo-random number.\n\nRead more about it here: https://wiki.nesdev.com/w/index.php/Random_number_generator\n\n## Variables\n\n2 bytes in the zeropage should be assigned to `prng_seed`\n\nThis variable should be initialized to any value except $00.\n\n## Methods\n\n`prng` - Generate new pseudo-random value (should be called once per frame)\n`prng_byte` - Load pseudo-random value into A register\n\n## Example\n\n```\n.rsset $0000\n\nprng_seed .rs 2\n\n;;;;;;;;\n\n.include <prng.h>\n\n;;;;;;;;\n\n    ; initialize seed\n    LDA #$13\n    STA seed\n    LDA #$37\n    STA seed+1\n\n    ; run prng\n    JSR prng\n\n    ; load pseudo-random byte into A register\n    JSR prng_byte\n\n    ; save value\n    STA <$12\n```\n\n','.ifndef prng_seed\n    .out "Please reserve 2 bytes in the zeropage for a `prng_seed` variable"\n.endif\n\n    JMP prng_guard\n\nprng:\n    ; save registers\n    PHA\n    TXA\n    PHA\n\n    LDX #$08\n    LDA <prng_seed\n\n    ; loop 8 times\nprng_loop:\n    ASL A\n    ROL <prng_seed+1\n    BCC prng_skip\n    EOR #$2D\nprng_skip:\n    DEX\n    BNE prng_loop\n    STA <prng_seed\n\n    PLA\n    TAX\n    PLA\n\n    RTS\n\n;;;;;;;;\n\nprng_byte:\n    LDA <prng_seed\n\n    RTS\n\nprng_guard:\n\n','prng','Pseudo-random number generator','1.0.1','GPLv3','random,rng,prng','2017-05-06 12:00:00','18d928d3cd93550c20291a19fdde3fe4a0d53672');
INSERT INTO `libs` VALUES (3,1,'# rle\n\nRun-length encoding (RLE) decoder\n\n## Explanation\n\n`rle` utilizes the run-length encoding used in many Konami games (Blades of Steel, Contra, etc). The format is:\n\n| Value | Meaning                                               |\n|-------|-------------------------------------------------------|\n| 00-80 | Read another byte, and write it to the output n times |\n| 81-FE | Copy n - 128 bytes from input to output               |\n| FF    | End of compressed data                                |\n\nThis library decompresses data and writes it directly to the `PPUDATA` ($2007) register. It is ideal for reading background data directly into video memory.\n\nRegisters clobbered: none\n\n## Variables\n\n2 bytes in the zeropage should be assigned to `rle_pointer`\n\n## Methods\n\n`rle` - Perform RLE decode\n\n## Example\n\n```\n.rsset $0000\n\nrle_pointer .rs 2\n\n;;;;;;;;\n\n.include <rle.asm>\n\n;;;;;;;;\n\n    ; set rle_pointer to data''s location\n    LDA #LOW(data)\n    STA rle_pointer\n    LDA #HIGH(data)\n    STA rle_pointer+1\n\n    ; perform RLE decode\n    JSR rle\n\n;;;;;;;;\n\ndata:\n    .db $04, $01, $84, $12, $34, $56, $78, $FF\n```\n\n','.ifndef rle_pointer\n    .out "Please reserve 2 bytes in the zeropage for a `rle_pointer` variable"\n.endif\n\n    JMP rle_guard\n\nrle:\n    ; save registers\n    PHA\n    TYA\n    PHA\n    TXA\n    PHA\n\n    LDY #$00\n\nrle_start:\n    ; load first byte\n    LDA [rle_pointer], Y\n\n    ; if 0xFF, rle is done\n    CMP #$FF\n    BEQ rle_done\n\n    ; if greater than 0x80, copy bytes directly\n    ; if less than or equal to 0x80, repeat next byte A times\n    CMP #$80\n    BCC rle_repeat\n\n    ; output byte string of length A\nrle_length:\n    AND #$7F\n    TAX\n    INY\n    BNE rle_length_loop\n    INC <rle_pointer+1\n\n    ; loop through bytes\nrle_length_loop:\n    LDA [rle_pointer], Y\n    STA $2007\n\n    INY\n    BNE rle_length_loop_continue\n    INC <rle_pointer+1\nrle_length_loop_continue:\n\n    DEX\n    BNE rle_length_loop\nrle_lenth_done:\n\n    ; read next byte\n    JMP rle_start\n\n    ; repeat next byte A number of times\nrle_repeat:\n    TAX\n    INY\n    BNE rle_repeat_continue\n    INC <rle_pointer+1\n\nrle_repeat_continue:\n    LDA [rle_pointer], Y\n\n    ; loop through bytes\nrle_repeat_loop:\n    STA $2007\n    DEX\n    BNE rle_repeat_loop\n\n    INY\n    BNE rle_repeat_done\n    INC <rle_pointer+1\nrle_repeat_done:\n\n    ; read next byte\n    JMP rle_start\n\nrle_done:\n    ; restore registers\n    PLA\n    TAX\n    PLA\n    TAY\n    PLA\n\n    RTS\n\nrle_guard:\n\n','rle','Run-length encoding (RLE) decoder','1.0.1','GPLv3','rle,encoding,decoding,compression','2017-05-06 12:00:00','618874e8a50ad8ff14454da1bc49c7ae2ec5d9a3');
CREATE TABLE `reference` (
	`id`	INTEGER,
	`parent_id`	INTEGER,
	`term`	VARCHAR(32),
	`text`	TEXT,
	PRIMARY KEY(`id`)
);
INSERT INTO `reference` VALUES (1,0,'registers','');
INSERT INTO `reference` VALUES (2,0,'addressing','');
INSERT INTO `reference` VALUES (3,0,'mappers','');
INSERT INTO `reference` VALUES (4,1,'PPUCTRL','');
INSERT INTO `reference` VALUES (5,1,'PPUMASK','');
INSERT INTO `reference` VALUES (6,1,'PPUSTATUS','');
INSERT INTO `reference` VALUES (7,1,'OAMADDR','');
INSERT INTO `reference` VALUES (8,1,'OAMDATA','');
INSERT INTO `reference` VALUES (9,1,'PPUSCROLL','');
INSERT INTO `reference` VALUES (10,1,'PPUADDR','');
INSERT INTO `reference` VALUES (11,1,'PPUDATA','');
INSERT INTO `reference` VALUES (12,1,'SQ1VOL','');
INSERT INTO `reference` VALUES (13,1,'SQ1SWEEP','');
INSERT INTO `reference` VALUES (14,1,'SQ1LO','');
INSERT INTO `reference` VALUES (15,1,'SQ1HI','');
INSERT INTO `reference` VALUES (16,1,'SQ2VOL','');
INSERT INTO `reference` VALUES (17,1,'SQ2SWEEP','');
INSERT INTO `reference` VALUES (18,1,'SQ2LO','');
INSERT INTO `reference` VALUES (19,1,'SQ2HI','');
INSERT INTO `reference` VALUES (20,1,'TRILINEAR','');
INSERT INTO `reference` VALUES (21,1,'TRILO','');
INSERT INTO `reference` VALUES (22,1,'TRIHI','');
INSERT INTO `reference` VALUES (23,1,'NOISEVOL','');
INSERT INTO `reference` VALUES (24,1,'NOISELO','');
INSERT INTO `reference` VALUES (25,1,'NOISEHI','');
INSERT INTO `reference` VALUES (26,1,'DMCFREQ','');
INSERT INTO `reference` VALUES (27,1,'DMCRAW','');
INSERT INTO `reference` VALUES (28,1,'DMCSTART','');
INSERT INTO `reference` VALUES (29,1,'DMCLEN','');
INSERT INTO `reference` VALUES (30,2,'accumulator','');
INSERT INTO `reference` VALUES (31,2,'implied','');
INSERT INTO `reference` VALUES (32,2,'immediate','');
INSERT INTO `reference` VALUES (33,2,'relative','');
INSERT INTO `reference` VALUES (34,2,'zeropage','');
INSERT INTO `reference` VALUES (35,2,'zeropage-x','');
INSERT INTO `reference` VALUES (36,2,'zeropage-y','');
INSERT INTO `reference` VALUES (37,2,'absolute','');
INSERT INTO `reference` VALUES (38,2,'absolute-x','');
INSERT INTO `reference` VALUES (39,2,'absolute-y','');
INSERT INTO `reference` VALUES (40,2,'indirect','');
INSERT INTO `reference` VALUES (41,2,'indirect-x','');
INSERT INTO `reference` VALUES (42,2,'indirect-y','');
INSERT INTO `reference` VALUES (43,3,'0','');
INSERT INTO `reference` VALUES (44,3,'1','');
INSERT INTO `reference` VALUES (45,3,'2','');
INSERT INTO `reference` VALUES (46,3,'3','');
INSERT INTO `reference` VALUES (47,3,'4','');
INSERT INTO `reference` VALUES (48,3,'5','');
INSERT INTO `reference` VALUES (49,3,'6','');
INSERT INTO `reference` VALUES (50,3,'7','');
INSERT INTO `reference` VALUES (51,3,'8','');
INSERT INTO `reference` VALUES (52,3,'9','');
INSERT INTO `reference` VALUES (53,3,'10','');
INSERT INTO `reference` VALUES (54,3,'11','');
INSERT INTO `reference` VALUES (55,3,'12','');
INSERT INTO `reference` VALUES (56,3,'13','');
INSERT INTO `reference` VALUES (57,3,'14','');
INSERT INTO `reference` VALUES (58,3,'15','');
INSERT INTO `reference` VALUES (59,3,'16','');
INSERT INTO `reference` VALUES (60,3,'17','');
INSERT INTO `reference` VALUES (61,3,'18','');
INSERT INTO `reference` VALUES (62,3,'19','');
INSERT INTO `reference` VALUES (63,3,'20','');
INSERT INTO `reference` VALUES (64,3,'21','');
INSERT INTO `reference` VALUES (65,3,'22','');
INSERT INTO `reference` VALUES (66,3,'23','');
INSERT INTO `reference` VALUES (67,3,'24','');
INSERT INTO `reference` VALUES (68,3,'25','');
INSERT INTO `reference` VALUES (69,3,'26','');
INSERT INTO `reference` VALUES (70,3,'27','');
INSERT INTO `reference` VALUES (71,3,'28','');
INSERT INTO `reference` VALUES (72,3,'29','');
INSERT INTO `reference` VALUES (73,3,'30','');
INSERT INTO `reference` VALUES (74,3,'31','');
INSERT INTO `reference` VALUES (75,3,'32','');
INSERT INTO `reference` VALUES (76,3,'33','');
INSERT INTO `reference` VALUES (77,3,'34','');
INSERT INTO `reference` VALUES (78,3,'35','');
INSERT INTO `reference` VALUES (79,3,'36','');
INSERT INTO `reference` VALUES (80,3,'37','');
INSERT INTO `reference` VALUES (81,3,'38','');
INSERT INTO `reference` VALUES (82,3,'39','');
INSERT INTO `reference` VALUES (83,3,'40','');
INSERT INTO `reference` VALUES (84,3,'41','');
INSERT INTO `reference` VALUES (85,3,'42','');
INSERT INTO `reference` VALUES (86,3,'43','');
INSERT INTO `reference` VALUES (87,3,'44','');
INSERT INTO `reference` VALUES (88,3,'45','');
INSERT INTO `reference` VALUES (89,3,'46','');
INSERT INTO `reference` VALUES (90,3,'47','');
INSERT INTO `reference` VALUES (91,3,'48','');
INSERT INTO `reference` VALUES (92,3,'49','');
INSERT INTO `reference` VALUES (93,3,'50','');
INSERT INTO `reference` VALUES (94,3,'51','');
INSERT INTO `reference` VALUES (95,3,'52','');
INSERT INTO `reference` VALUES (96,3,'53','');
INSERT INTO `reference` VALUES (97,3,'54','');
INSERT INTO `reference` VALUES (98,3,'55','');
INSERT INTO `reference` VALUES (99,3,'56','');
INSERT INTO `reference` VALUES (100,3,'57','');
INSERT INTO `reference` VALUES (101,3,'58','');
INSERT INTO `reference` VALUES (102,3,'59','');
INSERT INTO `reference` VALUES (103,3,'60','');
INSERT INTO `reference` VALUES (104,3,'61','');
INSERT INTO `reference` VALUES (105,3,'62','');
INSERT INTO `reference` VALUES (106,3,'63','');
INSERT INTO `reference` VALUES (107,3,'64','');
INSERT INTO `reference` VALUES (108,3,'65','');
INSERT INTO `reference` VALUES (109,3,'66','');
INSERT INTO `reference` VALUES (110,3,'67','');
INSERT INTO `reference` VALUES (111,3,'68','');
INSERT INTO `reference` VALUES (112,3,'69','');
INSERT INTO `reference` VALUES (113,3,'70','');
INSERT INTO `reference` VALUES (114,3,'71','');
INSERT INTO `reference` VALUES (115,3,'72','');
INSERT INTO `reference` VALUES (116,3,'73','');
INSERT INTO `reference` VALUES (117,3,'74','');
INSERT INTO `reference` VALUES (118,3,'75','');
INSERT INTO `reference` VALUES (119,3,'76','');
INSERT INTO `reference` VALUES (120,3,'77','');
INSERT INTO `reference` VALUES (121,3,'78','');
INSERT INTO `reference` VALUES (122,3,'79','');
INSERT INTO `reference` VALUES (123,3,'80','');
INSERT INTO `reference` VALUES (124,3,'81','');
INSERT INTO `reference` VALUES (125,3,'82','');
INSERT INTO `reference` VALUES (126,3,'83','');
INSERT INTO `reference` VALUES (127,3,'84','');
INSERT INTO `reference` VALUES (128,3,'85','');
INSERT INTO `reference` VALUES (129,3,'86','');
INSERT INTO `reference` VALUES (130,3,'87','');
INSERT INTO `reference` VALUES (131,3,'88','');
INSERT INTO `reference` VALUES (132,3,'89','');
INSERT INTO `reference` VALUES (133,3,'90','');
INSERT INTO `reference` VALUES (134,3,'91','');
INSERT INTO `reference` VALUES (135,3,'92','');
INSERT INTO `reference` VALUES (136,3,'93','');
INSERT INTO `reference` VALUES (137,3,'94','');
INSERT INTO `reference` VALUES (138,3,'95','');
INSERT INTO `reference` VALUES (139,3,'96','');
INSERT INTO `reference` VALUES (140,3,'97','');
INSERT INTO `reference` VALUES (141,3,'98','');
INSERT INTO `reference` VALUES (142,3,'99','');
INSERT INTO `reference` VALUES (143,3,'100','');
INSERT INTO `reference` VALUES (144,3,'101','');
INSERT INTO `reference` VALUES (145,3,'102','');
INSERT INTO `reference` VALUES (146,3,'103','');
INSERT INTO `reference` VALUES (147,3,'104','');
INSERT INTO `reference` VALUES (148,3,'105','');
INSERT INTO `reference` VALUES (149,3,'106','');
INSERT INTO `reference` VALUES (150,3,'107','');
INSERT INTO `reference` VALUES (151,3,'108','');
INSERT INTO `reference` VALUES (152,3,'109','');
INSERT INTO `reference` VALUES (153,3,'110','');
INSERT INTO `reference` VALUES (154,3,'111','');
INSERT INTO `reference` VALUES (155,3,'112','');
INSERT INTO `reference` VALUES (156,3,'113','');
INSERT INTO `reference` VALUES (157,3,'114','');
INSERT INTO `reference` VALUES (158,3,'115','');
INSERT INTO `reference` VALUES (159,3,'116','');
INSERT INTO `reference` VALUES (160,3,'117','');
INSERT INTO `reference` VALUES (161,3,'118','');
INSERT INTO `reference` VALUES (162,3,'119','');
INSERT INTO `reference` VALUES (163,3,'120','');
INSERT INTO `reference` VALUES (164,3,'121','');
INSERT INTO `reference` VALUES (165,3,'122','');
INSERT INTO `reference` VALUES (166,3,'123','');
INSERT INTO `reference` VALUES (167,3,'124','');
INSERT INTO `reference` VALUES (168,3,'125','');
INSERT INTO `reference` VALUES (169,3,'126','');
INSERT INTO `reference` VALUES (170,3,'127','');
INSERT INTO `reference` VALUES (171,3,'128','');
INSERT INTO `reference` VALUES (172,3,'129','');
INSERT INTO `reference` VALUES (173,3,'130','');
INSERT INTO `reference` VALUES (174,3,'131','');
INSERT INTO `reference` VALUES (175,3,'132','');
INSERT INTO `reference` VALUES (176,3,'133','');
INSERT INTO `reference` VALUES (177,3,'134','');
INSERT INTO `reference` VALUES (178,3,'135','');
INSERT INTO `reference` VALUES (179,3,'136','');
INSERT INTO `reference` VALUES (180,3,'137','');
INSERT INTO `reference` VALUES (181,3,'138','');
INSERT INTO `reference` VALUES (182,3,'139','');
INSERT INTO `reference` VALUES (183,3,'140','');
INSERT INTO `reference` VALUES (184,3,'141','');
INSERT INTO `reference` VALUES (185,3,'142','');
INSERT INTO `reference` VALUES (186,3,'143','');
INSERT INTO `reference` VALUES (187,3,'144','');
INSERT INTO `reference` VALUES (188,3,'145','');
INSERT INTO `reference` VALUES (189,3,'146','');
INSERT INTO `reference` VALUES (190,3,'147','');
INSERT INTO `reference` VALUES (191,3,'148','');
INSERT INTO `reference` VALUES (192,3,'149','');
INSERT INTO `reference` VALUES (193,3,'150','');
INSERT INTO `reference` VALUES (194,3,'151','');
INSERT INTO `reference` VALUES (195,3,'152','');
INSERT INTO `reference` VALUES (196,3,'153','');
INSERT INTO `reference` VALUES (197,3,'154','');
INSERT INTO `reference` VALUES (198,3,'155','');
INSERT INTO `reference` VALUES (199,3,'156','');
INSERT INTO `reference` VALUES (200,3,'157','');
INSERT INTO `reference` VALUES (201,3,'158','');
INSERT INTO `reference` VALUES (202,3,'159','');
INSERT INTO `reference` VALUES (203,3,'160','');
INSERT INTO `reference` VALUES (204,3,'161','');
INSERT INTO `reference` VALUES (205,3,'162','');
INSERT INTO `reference` VALUES (206,3,'163','');
INSERT INTO `reference` VALUES (207,3,'164','');
INSERT INTO `reference` VALUES (208,3,'165','');
INSERT INTO `reference` VALUES (209,3,'166','');
INSERT INTO `reference` VALUES (210,3,'167','');
INSERT INTO `reference` VALUES (211,3,'168','');
INSERT INTO `reference` VALUES (212,3,'169','');
INSERT INTO `reference` VALUES (213,3,'170','');
INSERT INTO `reference` VALUES (214,3,'171','');
INSERT INTO `reference` VALUES (215,3,'172','');
INSERT INTO `reference` VALUES (216,3,'173','');
INSERT INTO `reference` VALUES (217,3,'174','');
INSERT INTO `reference` VALUES (218,3,'175','');
INSERT INTO `reference` VALUES (219,3,'176','');
INSERT INTO `reference` VALUES (220,3,'177','');
INSERT INTO `reference` VALUES (221,3,'178','');
INSERT INTO `reference` VALUES (222,3,'179','');
INSERT INTO `reference` VALUES (223,3,'180','');
INSERT INTO `reference` VALUES (224,3,'181','');
INSERT INTO `reference` VALUES (225,3,'182','');
INSERT INTO `reference` VALUES (226,3,'183','');
INSERT INTO `reference` VALUES (227,3,'184','');
INSERT INTO `reference` VALUES (228,3,'185','');
INSERT INTO `reference` VALUES (229,3,'186','');
INSERT INTO `reference` VALUES (230,3,'187','');
INSERT INTO `reference` VALUES (231,3,'188','');
INSERT INTO `reference` VALUES (232,3,'189','');
INSERT INTO `reference` VALUES (233,3,'190','');
INSERT INTO `reference` VALUES (234,3,'191','');
INSERT INTO `reference` VALUES (235,3,'192','');
INSERT INTO `reference` VALUES (236,3,'193','');
INSERT INTO `reference` VALUES (237,3,'194','');
INSERT INTO `reference` VALUES (238,3,'195','');
INSERT INTO `reference` VALUES (239,3,'196','');
INSERT INTO `reference` VALUES (240,3,'197','');
INSERT INTO `reference` VALUES (241,3,'198','');
INSERT INTO `reference` VALUES (242,3,'199','');
INSERT INTO `reference` VALUES (243,3,'200','');
INSERT INTO `reference` VALUES (244,3,'201','');
INSERT INTO `reference` VALUES (245,3,'202','');
INSERT INTO `reference` VALUES (246,3,'203','');
INSERT INTO `reference` VALUES (247,3,'204','');
INSERT INTO `reference` VALUES (248,3,'205','');
INSERT INTO `reference` VALUES (249,3,'206','');
INSERT INTO `reference` VALUES (250,3,'207','');
INSERT INTO `reference` VALUES (251,3,'208','');
INSERT INTO `reference` VALUES (252,3,'209','');
INSERT INTO `reference` VALUES (253,3,'210','');
INSERT INTO `reference` VALUES (254,3,'211','');
INSERT INTO `reference` VALUES (255,3,'212','');
INSERT INTO `reference` VALUES (256,3,'213','');
INSERT INTO `reference` VALUES (257,3,'214','');
INSERT INTO `reference` VALUES (258,3,'215','');
INSERT INTO `reference` VALUES (259,3,'216','');
INSERT INTO `reference` VALUES (260,3,'217','');
INSERT INTO `reference` VALUES (261,3,'218','');
INSERT INTO `reference` VALUES (262,3,'219','');
INSERT INTO `reference` VALUES (263,3,'220','');
INSERT INTO `reference` VALUES (264,3,'221','');
INSERT INTO `reference` VALUES (265,3,'222','');
INSERT INTO `reference` VALUES (266,3,'223','');
INSERT INTO `reference` VALUES (267,3,'224','');
INSERT INTO `reference` VALUES (268,3,'225','');
INSERT INTO `reference` VALUES (269,3,'226','');
INSERT INTO `reference` VALUES (270,3,'227','');
INSERT INTO `reference` VALUES (271,3,'228','');
INSERT INTO `reference` VALUES (272,3,'229','');
INSERT INTO `reference` VALUES (273,3,'230','');
INSERT INTO `reference` VALUES (274,3,'231','');
INSERT INTO `reference` VALUES (275,3,'232','');
INSERT INTO `reference` VALUES (276,3,'233','');
INSERT INTO `reference` VALUES (277,3,'234','');
INSERT INTO `reference` VALUES (278,3,'235','');
INSERT INTO `reference` VALUES (279,3,'236','');
INSERT INTO `reference` VALUES (280,3,'237','');
INSERT INTO `reference` VALUES (281,3,'238','');
INSERT INTO `reference` VALUES (282,3,'239','');
INSERT INTO `reference` VALUES (283,3,'240','');
INSERT INTO `reference` VALUES (284,3,'241','');
INSERT INTO `reference` VALUES (285,3,'242','');
INSERT INTO `reference` VALUES (286,3,'243','');
INSERT INTO `reference` VALUES (287,3,'244','');
INSERT INTO `reference` VALUES (288,3,'245','');
INSERT INTO `reference` VALUES (289,3,'246','');
INSERT INTO `reference` VALUES (290,3,'247','');
INSERT INTO `reference` VALUES (291,3,'248','');
INSERT INTO `reference` VALUES (292,3,'249','');
INSERT INTO `reference` VALUES (293,3,'250','');
INSERT INTO `reference` VALUES (294,3,'251','');
INSERT INTO `reference` VALUES (295,3,'252','');
INSERT INTO `reference` VALUES (296,3,'253','');
INSERT INTO `reference` VALUES (297,3,'254','');
INSERT INTO `reference` VALUES (298,3,'255','');
INSERT INTO `reference` VALUES (299,4,'','PPUCTRL ($2000)\n\nDescription: PPU control register\nAccess:      Write\n\nVarious flags controlling PPU operation\n\n7  bit  0\n---- ----\nVPHB SINN\n|||| ||||\n|||| ||++- Base nametable address\n|||| ||    (0 = $2000; 1 = $2400; 2 = $2800; 3 = $2C00)\n|||| |+--- VRAM address increment per CPU read/write of PPUDATA\n|||| |     (0: add 1, going across; 1: add 32, going down)\n|||| +---- Sprite pattern table address for 8x8 sprites\n||||       (0: $0000; 1: $1000; ignored in 8x16 mode)\n|||+------ Background pattern table address (0: $0000; 1: $1000)\n||+------- Sprite size (0: 8x8; 1: 8x16)\n|+-------- PPU master/slave select\n|          (0: read backdrop from EXT pins; 1: output color on EXT pins)\n+--------- Generate an NMI at the start of the\n           vertical blanking interval (0: off; 1: on)');
INSERT INTO `reference` VALUES (300,5,'','PPUMASK ($2001)\n\nDescription: PPU mask register\nAccess:      Write\n\nThis register controls the rendering of sprites and backgrounds, as well as colour effects.\n\n7  bit  0\n---- ----\nBGRs bMmG\n|||| ||||\n|||| |||+- Greyscale (0: normal color, 1: produce a greyscale display)\n|||| ||+-- 1: Show background in leftmost 8 pixels of screen, 0: Hide\n|||| |+--- 1: Show sprites in leftmost 8 pixels of screen, 0: Hide\n|||| +---- 1: Show background\n|||+------ 1: Show sprites\n||+------- Emphasize red*\n|+-------- Emphasize green*\n+--------- Emphasize blue*\n\n* NTSC colors. PAL and Dendy swaps green and red');
INSERT INTO `reference` VALUES (301,6,'','PPUSTATUS ($2002)\n\nDescription: PPU status register\nAccess:      Read\n\nThis register reflects the state of various functions inside the PPU. It is often used for determining timing. To determine when the PPU has reached a given pixel of the screen, put an opaque pixel of sprite 0 there.\n\n7  bit  0\n---- ----\nVSO. ....\n|||| ||||\n|||+-++++- Least significant bits previously written into a PPU register\n|||        (due to register not being updated for this address)\n||+------- Sprite overflow. The intent was for this flag to be set\n||         whenever more than eight sprites appear on a scanline, but a\n||         hardware bug causes the actual behavior to be more complicated\n||         and generate false positives as well as false negatives; see\n||         PPU sprite evaluation. This flag is set during sprite\n||         evaluation and cleared at dot 1 (the second dot) of the\n||         pre-render line.\n|+-------- Sprite 0 Hit.  Set when a nonzero pixel of sprite 0 overlaps\n|          a nonzero background pixel; cleared at dot 1 of the pre-render\n|          line.  Used for raster timing.\n+--------- Vertical blank has started (0: not in vblank; 1: in vblank).\n           Set at dot 1 of line 241 (the line *after* the post-render\n           line); cleared after reading $2002 and at dot 1 of the\n           pre-render line.');
INSERT INTO `reference` VALUES (302,7,'','OAMADDR ($2003)\n\nDescription: OAM address port\nAccess:      Write\n\nWrite the address of OAM you want to access here. Most games just write $00 here and then use OAMDMA. (DMA is implemented in the 2A03/7 chip and works by repeatedly writing to OAMDATA)');
INSERT INTO `reference` VALUES (303,8,'','OAMDATA ($2004)\n\nDescription: OAM data port\nAccess:      Read, Write\n\nWrite OAM data here. Writes will increment OAMADDR after the write; reads during vertical or forced blanking return the value from OAM at that address but do not increment.');
INSERT INTO `reference` VALUES (304,9,'','PPUSCROLL ($2005)\n\nDescription: PPU scrolling position register\nAccess:      Write (x2)\n\nThis register is used to change the scroll position, that is, to tell the PPU which pixel of the nametable selected through PPUCTRL should be at the top left corner of the rendered screen. Typically, this register is written to during vertical blanking, so that the next frame starts rendering from the desired location, but it can also be modified during rendering in order to split the screen. Changes made to the vertical scroll during rendering will only take effect on the next frame.');
INSERT INTO `reference` VALUES (305,10,'','PPUADDR ($2006)\n\nDescription: PPU address register\nAccess:      Write (x2)\n\nBecause the CPU and the PPU are on separate buses,'' neither has direct access to the other''''s memory. The CPU writes to VRAM through a pair of registers on the PPU. First it loads an address into PPUADDR'', and then it writes repeatedly to PPUDATA to fill VRAM.');
INSERT INTO `reference` VALUES (306,11,'','PPUDATA ($2007)\n\nDescription: PPU data port\nAccess:      Read, Write\n\nVRAM read/write data register. After access, the video memory address will increment by an amount determined by $2000:2.');
INSERT INTO `reference` VALUES (307,12,'','SQ1VOL ($4000)\n\nDescription: Duty and volume for square channel 1\nAccess:      Write\n\nVarious flags controlling SQ1VOL operation\n\n7  bit  0\n---- ----\nDDLC VVVV\n|||| ||||\n|||| ++++- Volume/envelope\n|||+------ Constant volume\n||+------- Envelope loop/length counter halt\n++-------- Duty cycle\n');
INSERT INTO `reference` VALUES (308,13,'','SQ1SWEEP ($4001)\n\nDescription: Sweep control register for square channel 1\nAccess:      Write\n\nVarious flags controlling SQ1SWEEP operation\n\n7  bit  0\n---- ----\nEPPP NSSS\n|||| ||||\n|||| |+++- Sweep shift\n|||| +---- Sweep negate\n|+++------ Sweep period\n+--------- Sweep enabled\n');
INSERT INTO `reference` VALUES (309,14,'','SQ1LO ($4002)\n\nDescription: Low byte of period for square channel 1\nAccess:      Write\n\nVarious flags controlling SQ1LO operation\n\n7  bit  0\n---- ----\nTTTT TTTT\n|||| ||||\n++++ ++++- Timer low\n');
INSERT INTO `reference` VALUES (310,15,'','SQ1HI ($4003)\n\nDescription: High byte of period for square channel 1\nAccess:      Write\n\nVarious flags controlling SQ1_HI operation\n\n7  bit  0\n---- ----\nLLLL LTTT\n|||| ||||\n|||| |+++- Timer high\n++++ +---- Length counter load');
INSERT INTO `reference` VALUES (311,16,'','SQ2VOL ($4004)\n\nDescription: Duty and volume for square channel 2\nAccess:      Write\n\nVarious flags controlling SQ2VOL operation\n\n7  bit  0\n---- ----\nDDLC VVVV\n|||| ||||\n|||| ++++- Volume/envelope\n|||+------ Constant volume\n||+------- Envelope loop/length counter halt\n++-------- Duty cycle\n');
INSERT INTO `reference` VALUES (312,17,'','SQ2SWEEP ($4005)\n\nDescription: Sweep control register for square channel 2\nAccess:      Write\n\nVarious flags controlling SQ2SWEEP operation\n\n7  bit  0\n---- ----\nEPPP NSSS\n|||| ||||\n|||| |+++- Sweep shift\n|||| +---- Sweep negate\n|+++------ Sweep period\n+--------- Sweep enabled\n');
INSERT INTO `reference` VALUES (313,18,'','SQ2LO ($4006)\n\nDescription: Low byte of period for square channel 2\nAccess:      Write\n\nVarious flags controlling SQ2LO operation\n\n7  bit  0\n---- ----\nTTTT TTTT\n|||| ||||\n++++ ++++- Timer low\n');
INSERT INTO `reference` VALUES (314,19,'','SQ2HI ($4007)\n\nDescription: High byte of period for square channel 2\nAccess:      Write\n\nVarious flags controlling SQ2HI operation\n\n7  bit  0\n---- ----\nLLLL LTTT\n|||| ||||\n|||| |+++- Timer high\n++++ +---- Length counter load');
INSERT INTO `reference` VALUES (315,20,'','TRILINEAR ($4008)\n\nDescription: Triangle wave linear counter\nAccess:      Write\n\nVarious flags controlling TRILINEAR operation\n\n7  bit  0\n---- ----\nCRRR RRRR\n|||| ||||\n|+++ ++++- Length counter disable\n+--- ----- Linear counter reload value');
INSERT INTO `reference` VALUES (316,21,'','TRILO ($400A)\n\nDescription: Low byte of timer\nAccess:      Write\n\nVarious flags controlling TRILO operation\n\n7  bit  0\n---- ----\nLLLL LLLL\n|||| ||||\n++++ ++++- Timer low');
INSERT INTO `reference` VALUES (317,22,'','TRIHI ($400B)\n\nDescription: High byte of timer and length counter load\nAccess:      White\n\nVarious flags controlling TRIHI operation\n\n7  bit  0\n---- ----\nLLLL LHHH\n|||| ||||\n|||| |+++- Timer high\n++++ +---- Length counter load');
INSERT INTO `reference` VALUES (318,23,'','NOISEVOL ($400C)\n\nDescription: Volume for noise generator\nAccess:      White\n\nVarious flags controlling NOISEVOL operation\n\n7  bit  0\n---- ----\n--LC NNNN\n  || ||||\n  || ++++- Envelope period/volume\n  |+ ----- Constant volume\n  +- ----- Loop enable');
INSERT INTO `reference` VALUES (319,24,'','NOISELO ($400E)\n\nDescription: Period and waveform shape for noise generator\nAccess:      White\n\nVarious flags controlling NOISELO operation\n\n7  bit  0\n---- ----\nL--- PPPP\n|    ||||\n|    ++++- Noise period\n+--- ----- Loop noise');
INSERT INTO `reference` VALUES (320,25,'','NOISEHI ($400F)\n\nDescription: Length counter value for noise generator\nAccess:      White\n\nVarious flags controlling NOISEHI operation\n\n7  bit  0\n---- ----\nLLLL L---\n|||| |\n++++ +---- Length counter load');
INSERT INTO `reference` VALUES (321,26,'','DMCFREQ ($4010)\n\nDescription: Play mode and frequency for DMC samples\nAccess:      White\n\nVarious flags controlling DMCFREQ operation\n\n7  bit  0\n---- ----\nIL-- FFFF\n||   ||||\n||   ++++- Frequency index\n|+-- ----- Loop sample\n+--- ----- IRQ enable');
INSERT INTO `reference` VALUES (322,27,'','DMCRAW ($4011)\n\nDescription: 7-bit DAC\nAccess:      White\n\nVarious flags controlling DMCRAW operation\n\n7  bit  0\n---- ----\n-DDD DDDD\n ||| ||||\n +++ ++++- Direct load');
INSERT INTO `reference` VALUES (323,28,'','DMCSTART ($4012)\n\nDescription: Start of DMC waveform\nAccess:      White\n\nVarious flags controlling DMCSTART operation\n\n7  bit  0\n---- ----\nAAAA AAAA\n|||| ||||\n++++ ++++- Sample address %11AAAAAA.AA000000');
INSERT INTO `reference` VALUES (324,29,'','DMCLEN ($4013)\n\nDescription: Length of DMC waveform\nAccess:      White\n\nVarious flags controlling DMCLEN operation\n\n7  bit  0\n---- ----\nLLLL LLLL\n|||| ||||\n++++ ++++- Sample length %0000LLLL.LLLL0001');
INSERT INTO `reference` VALUES (325,30,'','Accumulator\n\nThe Accumulator is implied as the operand, so no address needs to be specified.\n\nExample:\n\nASL A');
INSERT INTO `reference` VALUES (326,31,'','Implied\n\nThe operand is implied, so it does not need to be specified.\n\nExample:\n\nTXA');
INSERT INTO `reference` VALUES (327,32,'','Immediate\n\nThe operand is used directly to perform the computation.\n\nExample:\n\nLDA #$22');
INSERT INTO `reference` VALUES (328,33,'','Relative\n\nThe offset specified is added to the current address stored in the Program Counter (PC). Offsets can range from -128 to +127.\n\nExample:\n\nBPL $2D');
INSERT INTO `reference` VALUES (329,34,'','Zeropage\n\nA single byte specifies an address in the first page of memory ($00xx), also known as the zero page, and the byte at that address is used to perform the computation.\n\nExample:\n\nLDY <$02');
INSERT INTO `reference` VALUES (330,35,'','Zeropage, X\n\nThe value in X is added to the specified zero page address for a sum address. The value at the sum address is used to perform the computation.\n\nExample:\n\nLDA <$01, X');
INSERT INTO `reference` VALUES (331,36,'','Zeropage, Y\n\nThe value in Y is added to the specified zero page address for a sum address. The value at the sum address is used to perform the computation.\n\nExample:\n\nLDA <$01, Y');
INSERT INTO `reference` VALUES (332,37,'','Absolute\n\nA full 16-bit address is specified and the byte at that address is used to perform the computation.\n\nExample:\n\nLDX $D010');
INSERT INTO `reference` VALUES (333,38,'','Absolute, X\n\nThe value in X is added to the specified address for a sum address. The value at the sum address is used to perform the computation.\n\nExample:\n\nADC $C001, X');
INSERT INTO `reference` VALUES (334,39,'','Absolute, Y\n\nThe value in Y is added to the specified address for a sum address. The value at the sum address is used to perform the computation.\n\nExample:\n\nINC $F001, Y');
INSERT INTO `reference` VALUES (335,40,'','[Indirect]\n\nThe value at the specified zero page address is used. The little-endian address stored at the two-byte pair of sum address (LSB) and sum address plus one (MSB) is jumped to.\n\nExample:\n\nJMP [$02]');
INSERT INTO `reference` VALUES (336,41,'','[Indirect, X]\n\nThe value in X is added to the specified zero page address for a sum address. The little-endian address stored at the two-byte pair of sum address (LSB) and sum address plus one (MSB) is loaded and the value at that address is used to perform the computation.\n\nExample:\n\nSTA [$15, X]');
INSERT INTO `reference` VALUES (337,42,'','[Indirect],'' Y\n\nThe value in Y is added to the address at the little-endian address stored at the two-byte pair of the specified address (LSB) and the specified address plus one (MSB). The value at the sum address is used to perform the computation. Indeed addressing mode actually repeats exactly the accumulator register''''s digits.\n\nExample:\n\nLSR [$2A]'', Y');
INSERT INTO `reference` VALUES (338,43,'','NROM (Mapper 000)\n\nCompany:             Nintendo, others\nBoards:              NROM, HROM*, RROM, RTROM, SROM, STROM\nPRG ROM capacity:    16K or 32K\nPRG ROM window:      n/a\nPRG RAM capacity:    2K or 4K in Family Basic only\nPRG RAM window:      n/a\nCHR capacity:        8K\nCHR window:          n/a\nNametable mirroring: Fixed H or V,'' controlled by solder pads (*V only)\nBus conflicts:       Yes\nIRQ:                 No\nAudio:               No\niNES mappers:        000\n\nGames:\n\n10 Yard Fight\n10 Yard Fight (J)\n110 in 1 Menu\n1942 (J)\n58 In 1 Menu\n76 In 1 Menu\nAntarctic Adventure\nArkanoid\nAstro Robo Sasa\nB-Wings\nBack to the Future\nBalloon Fight\nBalloon Fight (PAL)\nBaltron\nBaseball\nBaseball (J)\nBattle City\nBinary Land\nBokosuka Wars\nBomberman (J)\nBurgertime (J)\nChack N'''' Pop\nChallenger\nChampionship Lode Runner\nClu Clu Land disk-to-nes conv.\nDefender 2\nDevil World\nDig Dug\nDig Dug 2 (J)\nDonkey Kong\nDonkey Kong 3\nDonkey Kong Jr.\nDonkey Kong Jr. Math\nDonkey Kong Jr. Sansuu Asobi\nDoor Door\nDough Boy\nDuck\nDuck Hunt\nElevator Action\nExcitebike\nExcitebike (PAL)\nExed Exes\nExerion\nF1 Race\nFamicom Typing Tutor (Dr PC Jr)\nFamicom Typing Tutor 2\nField Combat\nFlappy\nFormation Z\nFour Card Games\nFront Line\nGalaga (J)\nGalaxian\nGalg\nGame Genie\nGeimos\nGolf\nGomoku Narabe\nGyrodine\nHogan''''s Alley\nHydlide\nHydlide (J)\nHyper Olympic\nHyper Olympic - Tonosoma Edition\nHyper Sports\nIce Climber\nIce Climber (disk conversion)\nIce Hockey\nIce Hockey (disk coversion)\nIgo Sinan\nIkki\nJewelry\nJoust\nKarateka\nKinniku Man\nKung-Fu\nLode Runner (J)\nLot Lot\nLunar Ball\nMach Rider\nMacross\nMag Max (J)\nMappy\nMario Bros\nMighty Bomb Jack (J)\nMillipede\nMs. Pac-Man\nNaitou 9 Dan Shogi Hiden\nNinja Kun\nNuts and Milk\nObake no Qtarou\nOnyanko Town\nOthello (J)\nOthello (Disk conversion)\nPac-Land\nPac-Man\nPac-Man (Unlicensed Version)\nPac-Man (J)\nPachicom\nPenguin Kun Wars\nPinball\nPoo-Yan\nPopeye\nPopeye Eigo Asobi\nPortpia Renzoku Satsujin Jiken\nPyramid\nRaid on Bungling Bay\nRaid on Bungling Bay (J)\nRoad Fighter\nRobot Block (Stack-Up)\nRobot Gyro (Gyromite)\nRoute 16 Turbo\nSeicross\nSeicross (J)\nSky Destroyer\nSlalom\nSlalom (PAL)\nSoccer\nSoccer (Disk Conversion)\nSon Son\nSpace Invaders\nSpartan X\nSpelunker (J)\nSpy Vs. Spy (J)\nSqoon (J)\nStar Force (J)\nStar Gate\nStar Luster\nSuper Arabian\nSuper Dynamix Badminton\nSuper Mario Bros\nSuper Mario Bros (PAL)\nSuper Mario Bros (Disk Conv.)\nTag Team Pro Wrestling\nTag Team Wrestling\nTennis\nThexder\nTower of Druaga'', The\nTwinbee (Disk Conversion)\nUrban Champion\nVolguard 2\nVolleyball (Disk Conversion)\nWarpman\nWild Gunman\nWrecking Crew\nXevious (J)\nYie-Ar Kung-Fu\nYo Nin Uti Majyan\nZippy Race');
INSERT INTO `reference` VALUES (339,44,'','MMC1 (Mapper 001)\n\nCompany:             Nintendo, others\nGames:               390 in NesCartDB\nComplexity:          ASIC\nBoards:              SKROM, SLROM,SNROM, others\nPRG ROM capacity:    512K\nPRG ROM window:      16K + 16K fixed or 32K\nPRG RAM capacity:    32K\nPRG RAM window:      8K\nCHR capacity:        128K\nCHR window:          4K + 4K or 8K\nNametable mirroring: H, V, or 1, switchable\nBus conflicts:       No\nIRQ:                 No\nAudio:               No\niNES mappers:        001,105,'' 155\n\nGames:\n\n100 Kiyagyou\n720\n''''89 Dennou Hosi Uranai\nA-Ressya De Ikou\nAbadox\nAbadox (J)\nAcchi Kocchi Socchi\nAddams Family'', The\nAddams Family 2, The (Pugsley)\nAdventures in the Magic Kingdom\nAdventures of Bayou Billy\nAdventures of Bayou Billy (PAL)\nAdventures of Lolo\nAdventures of Lolo 3\nAdventures of Rad Gravity, The\nAdventures of Rad Gravity (PAL)\nAdventures of Tom Sawyer,'' The\nAir Fortress\nAir Fortress (J)\nAirwolf\nAirwolf (PAL)\nAl Unser Jr''''s Turbo Racing\nAlien Syndrome (J)\nAll Pro Basketball\nAmerican Dream\nAmerican Gladiators\nAnkoku Sinwa\nAnticipation\nArtelius\nAtlantis no Nazo\nAttack of the Killer Tomatoes\nBack to the Future 2/3\nBad News Baseball\nBad Street Brawler\nBaken Hissyougaku Gate-In\nBarbie\nBard''''s Tale'','' The\nBard''''s Tale'','' The (J)\nBard''''s Tale 2'','' The\nBarker Bill''''s Trick Shooting\nBart vs. the Space Mutants\nBaseball Simulator 1000\nBaseball Stars\nBaseball Stars (J)\nBases Loaded\nBases Loaded 2\nBattle Chess\nBattle of Olympus'','' The\nBattle Stadium\nBattle Storm\nBe-Bop High School\nBest Play Pro Yakyuu\nBest Play Pro Yakyuu 2\nBest Play Pro Yakyuu Special\nBig Bird''''s Hide and Speak\nBigfoot\nBikkuri Man World Gekitotu Sei Sensi\nBill and Ted''''s Excellent Adventure\nBionic Commando\nBirdy Rush\nBlaster Master\nBlaster Master (PAL)\nBloody Warriors\nBoulder Dash\nBoulder Dash (J)\nBoy and His Blob'','' A\nBreakthru\nBubble Bobble\nBubble Bobble (PAL)\nBugs Bunny''''s Crazy Castle\nCaptain Ed\nCaptain Silver\nCaptain Tsubasa\nCastlevania 2\nCastlevania 2 (PAL)\nCaveman Games\nChaos World\nChiller\nChip N'''' Dale - Rescue Rangers\nChip N'''' Dale - Rescue Rangers 2\nChip to Dale no Daisakusen\nChip to Dale no Daisakusen 2\nChoujin Sentai Jetman\nChoujin Ultra Baseball\nChugoku Jyansi Story Tonpuu\nChuka Taisen\nCircus Caper\nClash at Demonhead\nCobra Command\nCobra Command (J)\nCocoron\nConflict\nCool World\nCosmic Wars\nCosmo Police Galivan\nDai Meiro\nDai Senryaku\nDance Aerobics\nDarkman\nDarkwing Duck\nDatsugoku\nDay Dreamin'''' Davey\nDeep Dungeon 3\nDeep Dungeon 4\nDefender of the Crown\nDemon Sword\nDengeki Big Bang\nDerby Stallion\nDerby Stallion Zenkokuban\nDesert Commander\nDestiny of an Emperor\nDezaemon\nDie Hard (J)\nDonald Duck\nDonald Land\nDoraemon Gigzombi no Gyakusyuu\nDouble Dragon\nDouble Dragon (J)\nDouble Dragon (PAL)\nDr. Jekyll and Mr. Hyde\nDr. Mario\nDr. Mario (PAL)\nDragon Fighter\nDragon Quest 4\nDragon Warrior\nDragon Warrior 2\nDragon Warrior 3\nDragon Warrior 4\nDragons of Flame\nDungeon and Magic\nDungeon Kid\nDungeon Magic\nDusty Diamond All-Star Softball\nDynablaster\nDynowarz\nEggerland\nEliminator Boat Duel\nElite\nElysion\nEmo Yan no 10 Bai Pro Yakyuu\nExciting Rally\nF1 Built to Win\nFamicom Yakyuuban\nFamily Fued\nFaria\nFaria (J)\nFaxanadu\nFester''''s Quest\nFighting Golf\nFinal Fantasy\nFinal Fantasy I/II\nFinal Mission\nFlying Warriors\nFrankenstein\nFreedom Force\nGambler Jikochusin Ha\nGambler Jikochusin Ha 2\nGarfield\nGekikame Ninjaden\nGekitou Pro Wrestling\nGekitou Stadium\nGenghis Khan\nGenghis Khan (J)\nGhostbusters 2\nGhoul School\nGinga Eiyuu Densetsu\nGoal\nGodzilla\nGodzilla (J)\nGodzilla 2\nGolf ''''92'','' The\nGolf Grand Slam\nGolgo 13\nGolgo 13 (J)\nGozonji Yajikita Tindouchu\nGrand Master\nGreat Deal\nGreat Tank\nGuerilla War\nGunhed\nHaja no Fuuin\nHarlem Globetrotters\nHatris\nHeavy Shreddin''''\nHercules no Eikou 2\nHeroes of the Lance\nHeroes of the Lance (J)\nHillsfar (J)\nHirake Ponkikki\nHiryuu no Ken 2\nHiryuu no Ken SP Fighting Wars\nHissatu Dojo Yaburi\nHittra no Fukkatu\nHokuto no Ken 3\nHokuto no Ken 4\nHome Run Nighter\nHook\nHook (J)\nHoops\nHostages\nHototogisu\nHudson Hawk\nHyaku no Sekai no Monogatari\nHyokkori Hyoutan Jima\nI Love Softball\nIdol Hakkenden\nIgo Sinan ''''91\nIgo Sinan ''''93\nIkari Warriors 2\nIkari Warriors 3\nIkari Warriors 3 (J)\nIndiana Jones / Last Crusade\nInternational Cricket\nIron Tank\nItadaki Street\nJourney to Silius\nJyanbou Ozaki no Hole-in-One\nKabusiki Doujyou\nKame no Ongaesi\nKamen no Ninja Hanamaru\nKatteni Sirokuma\nKero Kero Keroppi 2\nKid Icarus\nKid Niki\nKiri no London Satsujin Jiken\nKiteretsu Daihyakka\nKnight Rider\nKoushien\nKuja Kuou\nKuja Kuou 2\nKyuukyoku Tiger\nLee Trevino''''s Fighting Golf\nLegend of the Ghost Lion'', The\nLegend of Zelda,'' The\nLegend of Zelda (-1 PRG Rev.)\nLemmings\nLittle League Baseball\nMad City\nMagic Darts\nMagic Johnson''''s Fast Break\nMagic of Scherezade'','' The\nMahou no Princess Minky Momo\nMaijin Eiyuuden Wataru Gaiden\nMajaventure\nMajyan RPG Dora Dora Dora\nManiac Mansion\nManiac Mansion (PAL)\nMario Open Golf\nMarusa no Onna\nMatsumoto Tooru no Kabusiki Hissyougaku 2\nMechanized Attack\nMega Man 2\nMeiji Ishin\nMeitantei Holmes\nMelville''''s Flame\nMetal Flame Psybuster\nMetal Mech\nMetroid\nMini-Putt\nMiracle Piano System\nMirai Sensei Lios\nMizusima Senji no Dai Koushien\nMoeru Oniisan\nMomotarou Densetsu\nMoney Game 2'','' The\nMonopoly\nMonopoly (J)\nMonster Maker\nMonster Party\nMorita no Shogi\nMotocross Champion\nMotor City Patrol\nMule\nMuppets Adventure\nMusashi no Bouken\nNavy Blue\nNekketsu Koukou Dodgeball\nNES Open Tournament Golf\nNinja Cop Saizou\nNinja Gaiden\nNinja Rahoi\nNinja Ryukenden\nNobunaga no Yabou Zenkokuban\nNobunaga''''s Ambition\nObochama Kun\nOhotuku Ni Kiyu\nOishinbo\nOperation Wolf\nOrb 3D\nOsomatsu Kun\nOverlord\nPachinko Daisakusen\nPachinko Daisakusen 2\nPachio Kun 2\nPalamedes (J)\nPalamedes 2\nParutena no Kagami\nPerfect Bowl\nPeter Pan and the Pirates\nPhantom Fighter\nPictionary\nPinball Quest\nPirates\nPlatoon\nPole to Finish\nPOW\nPredator\nPresident no Sentaku\nPrince Valiant\nPrincess Tomato in Salad Kingdom\nPuzslot\nRacket Attack\nRace America\nRad Racer\nRad Racer (PAL)\nRaf World\nRC Pro-Am\nRC Pro-Am (PAL)\nReigen Dousi\nRemote Control\nRescue:  The Embassy Mission\nRoad Man\nRoadblasters\nRobin Hood\nRobocop 2\nRobocop 3\nRocket Ranger\nRocketeer'','' The\nRockman 2\nRollerball\nRomance of the Three Kingdoms\nRomancia\nSabaku no Kitune\nSaint Seiya 2 [hacked?]\nSanada Jyuuyuusi\nSangokusi\nSarada no Kuni no Tomato Hime\nSatomi Hakkenden\nSCAT\nSekiryuu Ou\nSesame Street 123/ABC\nSesame Street ABC\nShadow Warrior\nShikin Jyou\nShin Satomi Hakkenden\nShingen The Ruler\nShinsenden\nShogun\nSijyou Saidai Quiz ou Ketteisen\nSilkworm\nSkate or Die 2\nSki or Die\nSky Kid\nSky Shark\nSMB / Duck Hunt / WC Track Meet\nSnake Rattle N'''' Roll\nSnake Rattle N'''' Roll (PAL)\nSnake''''s Revenge\nSnoopy''''s Magic Show\nSnow Bros\nSoftball Tengoku\nSpace Shuttle Project\nSpot\nSquare no Tom Sawyer\nStealth ATF\nStealth ATF (PAL)\nSted Iseki Wakusei no Yabou\nStreet Cop\nStrider\nSuper Black Onyx\nSuper Chinese Land 3\nSuper Dodge Ball\nSuper Momotarou Densetsu\nSuper Real Baseball\nSuperman\nSuperman (J)\nSwamp Thing\nSweet Home\nSyoukousi Sedy\nTaboo\nTaiyou no Sinden\nTakeda Shingen 2\nTale Spin\nTanikawa Kouji no Shogi Sinan 3\nTao\nTarget Renegade\nTashiro Musasi no Princess Galppai\nTatakae Ramen Man\nTecmo Baseball\nTecmo Bowl\nTecmo Cup Soccer\nTecmo World Wrestling\nTecmo World Wrestling (PAL)\nTeenage Mutant Hero Turtles\nTeenage Mutant Ninja Turtles\nTeenage Mutant Ninja Turtles PAL\nTenchi wo Kurau\nTetris\nTetris 2 + Bombliss\nThree Stooges'', The\nThunder and Lightning\nThunderbirds\nThunderbirds (J)\nTitan\nTombs and Treasure\nTonjan\nTop Players Tennis\nTouchdown Fever\nTouchdown Fever (J)\nTouhou Kenbunroku\nTrack and Field 2\nTrack and Field 2 (PAL)\nTriathron, The\nTsuppari Wars\nTurbo Racing\nUltima - Exodus\nUltima - Exodus (J)\nUltima - Quest of the Avatar\nUltima - Quest of the Avatar (J)\nUltima - Warriors of Destiny\nUntouchables, The\nVegas Connection\nVegas Dream\nVenus Wars, The\nViva Las Vegas\nWhite Lion Densetsu\nWillow\nWillow (J)\nWin, Lose,'' or Draw\nWizardry - Proving Grounds\nWizardry - Proving Grounds (J)\nWorld Boxing\nWorld Super Tennis\nWrath of the Black Manta\nXenophobe\nXexyz\nY''''s\nYo Noid\nYokohama Renzoku Satsujin Jiken\nYoshi\nYoshi no Tamago\nYousike Ide''''s Battle Mahjongg 2\nZelda no Densetsu\nZelda 2 - The Adventure of Link\nZelda 2 (PAL)\nZenbei Pro Basket\nZoids 2\nZombie Hunter''');
INSERT INTO `reference` VALUES (340,45,'','UNROM (Mapper 002)\n\nCompany:             Nintendo, others\nGames:               155 in NesCartDB\nComplexity:          Discrete logic\nBoards:              UNROM, UOROM\nPRG ROM capacity:    256K/4096K\nPRG ROM window:      16K + 16K fixed\nPRG RAM capacity:    None\nCHR capacity:        8K\nCHR window:          n/a\nNametable mirroring: Fixed H or V, controlled by solder pads\nBus conflicts:       Yes/No\nIRQ:                 No\nAudio:               No\niNES mappers:        002,94, 180\n\nGames:\n\n100 Man Doru Kid\n1943\n1943 (J)\n1944\nAigiina no Yogen\nAkumajo Dracula\nAlfred Chicken\nAlgos no Senshi\nAmagon\nArchon\nArctic\nAsterix (PAL)\nAthena\nAthena (J)\nAttack Animal Gakuen\nBallblazer\nBatu and Teree\nBest of the Best\nBlack Bass, The\nBlack Bass, The (J)\nBlack Bass 2, The\nBlades of Steel\nBlades of Steel (PAL)\nBlues Brothers,'' The\nBomber King\nBomberman 2 (J)\nBooby Kids\nCalifornia Games\nCasino Kid\nCastelian\nCastelian (PAL)\nCastle of Dragon\nCastlevania\nChampionship Pool\nChester Field\nChugoku Sensei Jyuutu\nConan\nContra\nCrackout\nDaiva\nDash Yarou\nDick Tracy\nDouble Dribble\nDr. Chaos\nDragon Quest 2\nDragon Quest 3\nDragon Unit\nDragon''''s Lair\nDucktales\nDucktales 2\nErunaaku no Zaihou\nEsupa Boukentai\nFamily Quiz\nFantasy Zone (J)\nFaxanadu (J)\nFinal Fantasy (J)\nFinal Fantasy 2\nFist of the North Star\nFlying Dragon\nFlying Hero\nFoton\nGaurdian Legend'',''  The\nGaurdic Gaiden\nGekitotu 4 Kubattle\nGhosts N'''' Goblins\nGilligan''''s Island\nGinga no Sannin\nGoonies 2'', The\nGoonies 2,'' The (J)\nGunsmoke\nGunsmoke (PAL)\nHana no Star Kaidou\nHanjuku Hero\nHatris (J)\nHector ''''87\nHello Kitty World\nHercules no Eikou\nHi no Tori\nHigemaru Makaijima\nHighway Star\nHiryuu no Ken\nHokuto no Ken 2\nHosi wo Miruhito\nHoumaga Toki\nIkari Warriors\nIkari Warriors (J)\nIkari Warriors 2 (J)\nIndra no Hikari\nJack Nicklaus Golf\nJackal\nJesus\nJimmy Connors Tennis\nJimmy Connors Tennis (PAL)\nJongbou\nJordan vs Bird\nKaguya Hime Densetsu\nKakefu-kun no Jump Tengoku\nKamen no Ninja Akakage\nKick Off\nKid Kool\nKlash Ball\nKyoro-chan Land\nLabyrinth\nLaw of the West\nLayla\nLegendary Wings\nLife Force\nLipple Island\nLittle Mermaid'', The\nLittle Mermaid, The (J)\nLoopz\nLost Word of Jenny,'' The\nMagunamu Kikiipatu\nMaison Ikkoku\nMajyou Densetsu 2\nMakaimura\nManiac Mansion (J)\nMatsumoto Tooru no Kabusiki Hissyougaku\nMega Man\nMeitantei Holmes Kori no London Satsujin Jiken\nMetal Gear\nMetal Gear (J)\nMiracle Ropit''''s Adventure in 2100\nMomotarou Dentetsu\nMottono Abunai Deka\nNangoku Seirei Spy vs Spy\nNekketsu Kouha Kunio Kun\nNFL Football\nNinja Kun Asyura no Saiyou\nOlympus no Tatakai\nOutlanders\nPaperboy 2\nPrince of Persia\nPro Wrestling\nPro Yakyuu Satsujin Jiken\nProbotector\nPuss N'''' Boots\nRainbow Island\nRambo\nRambo (J)\nRampart (J)\nRenegade\nRobowarrior\nRockman\nRush N'''' Attack\nRush N'''' Attack (PAL)\nRygar\nSaiyuuki World\nSalamander\nSection Z\nSeirei Gari\nSenjou no Ookami\nShanghai\nShanghai 2\nSherlock Holmes\nShufflepuck Cafe\nSide Pocket\nSilent Service\nSilent Service (PAL)\nSkate or Die\nSpace Harrier\nSpelunker 2\nStar Trek - The Next Generation\nStarship Hector\nStick Hunter\nStinger\nSukeban Deka 3\nSuper Cars\nSuper Glove Ball\nSuper Pinball\nSuper Pitfall\nSuper Pitfall (J)\nSuper Star Force\nSwat\nSwords and Serpents\nTakeda Shingen\nTakeshi no Chousen Jyou\nTantei Jingujii Saburou Tokino Sugiyukumamani\nTatakai no Banka\nTerra Cresta (J)\nThundercade\nTime Stranger\nTimes of Lore\nTobidase Daisakusen 2\nTop Gun\nTotal Recall\nTotsuzen Macyoman\nTouch\nTrog\nTrojan\nTrojan (PAL)\nTurikiti Sanpei Blue\nUddy Poko\nValis\nWall Street Kid\nWanpaku Duck Yumebouken\nWayne Gretzky Hockey\nWinter Games\nWits\nX-Men\nYousike Ide''''s Battle Mahjongg\nZanac\nZoids''');
INSERT INTO `reference` VALUES (341,46,'','CNROM (Mapper 003)\n\nCompany:             Nintendo, others\nGames:               104 in NesCartDB\nBoards:              CNROM "and similar"\nPRG ROM capacity:    16K or 32K\nPRG ROM window:      n/a\nPRG RAM capacity:    None\nCHR capacity:        32K (2M oversize version)\nCHR window:          8K\nNametable mirroring: Fixed H or V\nBus conflicts:       Yes(CNROM,'' some others)\nIRQ:                 No\nAudio:               One case\niNES mappers:        003\n\nGames:\n\nAdventure Island\nAdventures of Dino-Riki\nAlpha Mission\nArgus\nArmored Scrum Object\nAthletic World\nAV Pachi Slot\nBanana\nBird Week\nBrush Roller\nBuggy Popper\nBump N'''' Jump\nCadillac\nCastle Excellent\nChampionship Bowling (J)\nChoplifter\nChubby Cherub\nCircus Charlie\nCity Connection\nCity Connection (J)\nClu Clu Land\nCosmo Genesis\nCybernoid\nDash Galaxy in the Alien Asylum\nDeblock\nDonkey Kong Classics\nDragon Quest\nDrop Zone\nDynamite Bowl\nEgypt\nFamily BASIC\nFamily Trainer Running Stadium\nFleet Commander\nFlintstones'', The\nFlintstones, The (PAL)\nFlipull\nFriday The 13th\nGegege no Kitarou\nGhostbusters\nGhostbusters (J)\nGoonies,'' The\nGorby no Pipeline Daisakusen\nGotcha\nGradius (J)\nGyruss\nHello Kitty no Ohana Batake\nHokuto no Ken\nHot Slots\nHottaman no Titeitanken\nHyauti Super Igo\nIdol Shisen Mahjongg\nIkinari Musician\nJajamaru no Daibouken\nJaws\nJohn Elway''''s Quarterback\nKarate Champ\nKarate Kid'','' The\nKeisan Game Sansuu 2\nKeisan Game Sansuu 3\nKeisan Game Sansuu 4\nKeisan Game Sansuu 5/6 Nen\nKero Kero Keroppi\nKing''''s Knight\nKing''''s Knight (J)\nKings of the Beach\nKung-Fu Heroes\nLast Starfighter'', The\nLegend of Kage,'' The (J)\nMag Max\nMajor League Baseball\nMario China\nMeikyu Kumikyoko\nMickey Mouse\nMickey Mousecapade\nMilon''''s Secret Castle\nMinnie no Talabou Nakayosi Daisakusen\nMoai Kun\nMusashi no Ken\nMUSCLE\nMystery Quest\nNagagutu wo Haita Neko\nNinja Jajamaru Kun\nNinja Kid\nOryu San\nPaperboy\nPeepar Time\nPipe Dream\nPuznic\nPuzzle\nQ-Bert\nQuarth\nSanrio Carnival\nSanrio Cup Ponpon Bare\nSeikima 2\nShisen Mahjong Seifukuhen\nSinjinrui\nSmash Ping Pong (Disk Conv.)\nSoap Panic\nSolomon no Kagi\nSolomon''''s Key\nSpace Hunter\nSpy Hunter\nSqoon\nStar Force\nStar Soldier (J)\nStar Voyager\nSuper Monkey Daibouken\nSuper Team Games\nT&C Surf Design\nTakahasi Meijin no Boukenjima\nTetris (Tengen)\nTetris (J)\nTetudouou\nTiger-Heli (J)\nTokorosan no Mamoru\nToukaidou 53 Tugi\nTransformers Combo\nTsuppari Oozomou\nTwinbee\nUrusei Yatsura\nVolleyball\nWing of Madoola'', The');
INSERT INTO `reference` VALUES (342,47,'','MMC3 (Mapper 004)\n\nCompany:             Nintendo, others\nGames:               300 in NesCartDB\nComplexity:          ASIC\nBoards:              TSROM, others\nPRG ROM capacity:    512K\nPRG ROM window:      8K + 8K + 16K fixed\nPRG RAM capacity:    8K\nPRG RAM window:      8K\nCHR capacity:        256K\nCHR window:          2Kx2 + 1Kx4\nNametable mirroring: H or V, switchable, or 4 fixed\nBus conflicts:       No\nIRQ:                 Yes\nAudio:               No\niNES mappers:        004,118,'' 119\n\nGames:\n\n1999 Hore Mitakotoka Sekimatsu\n8 Eyes\n8 Eyes (J)\nAbarenbou Tengu\nAdventure Island 2\nAdventure Island 3\nAdventures of Lolo (J)\nAdventures of Lolo 2\nAdventures of Rocky & Bullwinkle\nAkira\nAkuma no Shoutaijou\nAlien 3\nAltered Beast\nAmerica Oudan no Ultra Quiz\nAnpan Man no Hiragana Daisuki\nAsmikkun Land\nAstyanax\nBabel no Tou\nBad Dudes\nBakusyou Jinsei Gekijyou 3\nBananan no Ouiji Daibouken\nBart vs. the World\nBartman Meets Radioactive Man\nBase Wars\nBaseball Stars 2\nBases Loaded 3\nBases Loaded 4\nBatman\nBatman (PAL)\nBatman Returns\nBill Elliot''''s NASCAR Challenge\nBlue Marlin'','' The\nBlue Shadow\nBo Jackson Baseball\nBubble Bobble 2\nBucky O'''' Hare\nBucky O'''' Hare (J)\nBucky O'''' Hare (PAL)\nBugs Bunny''''s Birthday Blowout\nBurai Fighter\nCapcom Barcelona ''''92\nCaptain America and the Avengers\nCaptain Planet\nCaptain Tsubasa 2\nCastlequest (J)\nCatts Nintouden Teyandey\nCaveman Ninja\nChase HQ\nChibi Marukochan Uki Uki Shopping\nChiyo no Fuji\nCliffhanger\nCode Name Viper\nColumbus Ougon no Yoake\nConquest of the Crystal Palace\nContra Force\nCosmic Epsilon\nCrash N'''' The Boys\nCrisis Force [hacked]\nCrossfire\nCrystalis\nCyberball\nDaikaijyuu Deburas\nDaiku no Gensan\nDark Lord\nDays of Thunder\nDefenders of Dynatron City\nDeja Vu\nDirty Harry\nDoki Doki Yuenchi\nDouble Dragon 2\nDouble Dragon 2 (J)\nDouble Dragon 3\nDouble Dragon 3 (J)\nDouble Dragon 3 (PAL)\nDoublemoon Densetsu\nDowntown Nekketsu Jidaigekidayo\nDowntown Nekketsu Kousinkyoko\nDowntown Nekketsu Monogatari\nDracula\nDracula (PAL)\nDragon Buster [hacked]\nDragon Buster 2\nDragon Slayer 4\nDragon Spirit\nDragon Strike\nDragon Wars\nEarthbound\nEmpire Strikes Back'','' The\nErika to Satoru no Yume Bouken\nF1 Circus\nF1 Hero\nF1 Hero 2\nF117A Stealth Fighter\nFaibird\nFamily Boxing\nFamily Circuit\nFamily Jockey\nFamily Majyan\nFamily Majyan 2\nFamily Pinball\nFamily Stadium\nFamily Stadium ''''87\nFamily Stadium ''''88\nFamily Stadium ''''89\nFamily Stadium ''''91\nFamily Stadium ''''92\nFamily Stadium ''''93\nFamily Stadium ''''94\nFamily Tennis\nFC Genjin\nFelix the Cat\nFinal Fantasy 3\nFire Emblem [hacked]\nFire Emblem Gaiden [hacked]\nFusigi no Umi no Nadia\nFuzzical Fighter\nGalaxy 5000\nGanbare Goemon 2 [hacked?]\nGargoyle''''s Quest 2\nGarou Densetsu Special [hacked]\nGauntlet\nGauntlet 2\nGauntlet 2 (PAL)\nGenpei Toumaden\nGeorge Foreman''''s KO Boxing\nGI Joe\nGI Joe -  The Atlantis Factor\nGod Slayer\nGold Medal Challenge ''''92\nGolgo 13 - The Mafat Conspiracy\nGolgo 13 - The Riddle of Icarus\nGremlins 2\nGunnac\nGunnac (J)\nHeavy Barrel\nHiryuu no Ken 3\nHissatu Sigotonin\nHome Alone\nHome Alone 2\nHome Run Nighter ''''90\nHosi no Kirby\nHunt For Red October'', The\nIke Ike Nekketsu Hockey\nImage Fight\nImmortal, The\nIncredible Crash Dummies,'' The\nIndiana Jones / Temple of Doom\nInfiltrator\nIsolated Warrior\nJ League - King of Ace Strikers\nJackie Chan\nJackie Chan''''s Action Kung-Fu\nJames Bond Jr.\nJames Bond Jr. (PAL)\nJarvas\nJetsons'','' The\nJikuuyuuden Debias\nJoe and Mac\nJoy Mecha Fight\nJumpin'''' Kid\nJungle Book'','' The\nJurassic Park\nKabuki Quantum Fighter\nKage\nKagerou Densetsu\nKaijyu Monogatari [hacked]\nKamen Rider SD\nKarnov\nKarnov (J)\nKart Fighter\nKawa no Nushi Tsuri\nKeiba Honmei\nKeru Naguru\nKick Master\nKickle Cubicle\nKid Klown\nKing Kong 2\nKing of Kings (J - diff. game)\nKing''''s Quest 5\nKirby''''s Adventure\nKiwi Kraze\nKlax (J)\nKonami Sport in Soul\nKrion Conquest'','' The\nKrusty''''s Fun House\nKrusty''''s Fun House (PAL)\nKurogane Hirosi no Keiba Densetu\nKyoto Hana no Missutu Satsujin Jiken\nKyoto Sesupensu Misa Yamamura Satsujin Jiken\nLast Armageddon\nLast Ninja'', The\nLegacy of the Wizard\nLegends of the Diamond\nLittle Nemo The Dream Master\nLittle Ninja Brothers\nLone Ranger,'' The\nLow G Man\nLupin 3rd Pandra Nolsan\nMad Max\nMagical Doropie\nMagician\nMappy Land\nMappy Land (J)\nMario is Missing\nMario''''s Time Machine\nMasuzoe Youiti no Asamade\nMaten Douji\nMax Warrior\nMcKids\nMega Man 3\nMega Man 4\nMega Man 4 (PAL)\nMega Man 5\nMega Man 6\nMegami Tensei\nMeimom Takonishi Ouendan\nMendel Palace\nMetal Max\nMetal Storm\nMetal Storm (J)\nMetro Cross\nMight and Magic\nMight and Magic (J)\nMighty Final Fight\nMighty Final Fight (J)\nMinelvation Saga\nMission Impossible\nMission Impossible (PAL)\nMitsume ga Tooru\nMomotarou Densetsu Gaiden\nMonster In My Pocket\nMonster In My Pocket (PAL)\nMoon Crystal\nMother\nMurder Club\nMy Life'', My Love\nNekketsu Kakutou Densetsu\nNekketsu Koukou Soccer\nNES Play Action Football\nNew Zealand Story,'' The\nNightshade\nNiji no Silkroad\nNingen Heiki Dead Fox\nNinja Gaiden 2\nNinja Gaiden 3\nNinja Ryukenden 2\nNinja Ryukenden 3\nNintendo World Cup\nNintendo World Cup (PAL)\nNoah''''s Ark\nNorth and South\nNyankies\nOtaku no Seiza\nOver Horizon\nPachi Slot Adventure 2\nPachi Slot Adventure 3\nPachio Kun 3\nPachio Kun 4\nPachio Kun 5 (Pachio Kun Jr)\nPanic Restaurant\nParallel World\nParasol Henbei\nParodius (PAL)\nPool of Radiance\nPool of Radiance (J)\nPower Blade\nPower Blade 2\nPower Punch 2\nProbotector 2\nProject Q\nPunisher'', The\nQuest of Kai,'' The\nQuinty\nRad Racer 2\nRadia Senki\nRampage\nRampart\nRasarulsii no Child''''s Quest\nRBI Baseball\nRBI Baseball 2\nRBI Baseball 3\nRecca: Summer Carnival ''''92\nRedalerma 2\nRen and Stimpy:  Buckaroo$\nRing King\nRiver City Ransom\nRoad Runner\nRobocco Wars\nRobocop\nRobocop Vs Terminator\nRock N'''' Ball\nRockin'''' Kats\nRockman 3\nRockman 4\nRockman 5\nRockman 6\nRoger Clemens MVP Baseball\nRollergames\nRolling Thunder\nRoundball\nRPG Life Game\nSanma no Meitantei\nSansa-Rana-Ga\nSD Gundam Gachapon Senshi 2\nSD Gundam Gachapon Senshi 3\nSD Gundam Gachapon Senshi 4\nSD Gundam Gachapon Senshi 5\nSD Hatori Daisakusen\nSD Hero Soukessen\nSD Sengoku Busyou Retsuden\nSeirei Densetsu Lickle\nShadow Brain\nShadow of the Ninja\nShadowgate\nShadowgate (J)\nShadowgate (Swedish)\nShaffle Fight\nShancara\nShatterhand\nShonen Ashibe\nSide Pocket (J)\nSilva Saga\nSilver Surfer\nSky Kid (J)\nSmash TV\nSMB / Tetris / Nint. World Cup\nSolomon no Kagi 2\nSoMari\nSpider-Man\nStanley\nStar Trek\nStar Wars\nStar Wars (J - Namco version)\nStar Wars (PAL)\nStartropics\nStartropics 2\nStreet Fighter 2010\nSugoro Quest\nSuper Chinese Land\nSuper Chinese Land 2\nSuper C\nSuper Contra\nSuper Donkey Kong 2\nSuper Express Satsujin Jiken\nSuper Mario Bros 2\nSuper Mario Bros 2 (-1 PRG rev.)\nSuper Mario Bros 3\nSuper Mario Bros 3 (-1 PRG Rev.)\nSuper Mario Bros 3 (J)\nSuper Mario Bros 3 (PAL)\nSuper Mario USA\nSuper Robot Taisen 2\nSuper Spike V''''Ball\nSuper Spike V''''Ball/Nintendo World Cup\nSuper Sprint\nSuper Spy Hunter\nSuper Turrican (PAL)\nSuper Xevious\nSword Master\nSword Master (J)\nT&C Surf Design 2\nTakahasi Meijin no Boukenjima 2\nTakahasi Meijin no Boukenjima 3\nTakahasi Meijin no Boukenjima 4\nTakeshi no Sengoku Fuunji\nTecmo NBA Basketball\nTecmo Super Bowl\nTeenage Mutant Ninja Turtles 2\nTeenage Mutant Ninja Turtles 3\nTenchi wo Kurau 2\nTerminator'','' The\nTerminator 2\nTerminator 2 (Beta Version)\nTerminator 2 (J)\nTetrastar\nTetris 2\nTetris 2 (PAL)\nTetris Flash\nTetsuwan Atom\nTime Zone\nTiny Toon Adventures\nTiny Toon Adventures 2\nTiny Toons Cartoon Workshop\nTitei Senkuu Bazoruda\nTM Network Live At Power Bowl\nToki\nTokyukyuu Seirei Solbrain\nTom and Jerry\nToobin''''\nTop Gun - The Second Mission\nTotally Rad\nToxic Crusaders\nTwin Cobra\nUltimate Air Combat\nUltimate Basketball\nUltraman Club 2\nUltraman Club 3\nUninvited\nUS Championship V''''Ball\nUturun Desu\nValkyure no Bouken\nVice - Project Doom\nVillgust Gaiden\nVindicators\nWacky Races\nWagyan Land\nWairi no Write Rockboard\nWanpaku Kokkun no Gurume World\nWario no Mori\nWario''''s Woods\nWarwolf\nWayne''''s World\nWCW Championship Wrestling\nWerewolf\nWestern Kids\nWhere in Time is Carmen Sandiego\nWhere''''s Waldo?\nWhomp ''''Em\nWidget\nWizardry - Knight of Diamonds\nWizardry - Knight of Diamonds(J)\nWizardry - Legacy of Lyllgamyn\nWolverine\nWurm\nWWF King of the Ring\nWWF Steel Cage Challenge\nWWF Steel Cage Challenge (PAL)\nY''''s 2\nY''''s 3\nYoshi no Cookie\nYoshi''''s Cookie\nYoung Indiana Jones Chronicles\nYume Penguin Monogatari (Hacked)\nZaiteku Satsujin Jiken\nZen - Intergalactic Ninja\nZoids 3\nZombie Nation''');
INSERT INTO `reference` VALUES (343,48,'','MMC5 (Mapper 005)\n\nCompany:             Nintendo, Koei, others\nGames:               14 in NesCartDB\nComplexity:          ASIC\nBoards:              ETROM, others\nPRG ROM capacity:    1024K\nPRG ROM window:      8K, 16K, or 32K\nPRG RAM capacity:    64K\nPRG RAM window:      8K\nCHR capacity:        1024K\nCHR window:          1K, 2K, 4K, or 8K\nNametable mirroring: arbitrary,'' up to 3 sourcenametables (plus fill mode)\nBus conflicts:       No\nIRQ:                 Yes\nAudio:               Yes\niNES mappers:        005\n\nGames:\n\nBandit Kings of Ancient China\nCastlevania 3\nGemfire\nGunsight\nJust Breed\nL''''Emperuer\nLaser Invasion\nMetal Slader Glory\nNobunaga''''s Ambition 2\nRomance of the Three Kingdoms 2\nUncharted Waters''');
INSERT INTO `reference` VALUES (344,49,'','FFE Rev. A (Mapper 006)\n\nGames:\n\nArabian Dream Sharezerd [hacked]\nDokugan Masamune [hacked]\nDragon Scroll [hacked]\nGanbare Goemon [hacked]\nGegege no Kitarou 2 [Hacked]\nMoney Game, The [Hacked]\nSaint Seiya [hacked]');
INSERT INTO `reference` VALUES (345,50,'','ANROM (Mapper 007)\n\nCompany:             Nintendo, Rare, others\nGames:               34 in NesCartDB\nComplexity:          Discrete logic\nBoards:              AMROM, ANROM, AN1ROM, AOROM,'' others\nPRG ROM capacity:    256K\nPRG ROM window:      32K\nPRG RAM capacity:    None\nPRG RAM window:      n/a\nCHR capacity:        8K\nCHR window:          n/a\nNametable mirroring: 1 page switchable\nBus conflicts:       AMROM/AOROM only\nIRQ:                 No\nAudio:               No\niNES mappers:        007\n\nGames:\n\nArch Rivals\nBattletoads\nBattletoads (PAL)\nBattletoads / Double Dragon\nBeetlejuice\nCabal\nCaesar''''s Palace\nCaptain Skyhawk\nCobra Triangle\nCobra Triangle (PAL)\nCommando\nDanny Sullivan''''s Indy Heat\nDensetsu no Kisi Elrond\nDigger T. Rock\nDouble Dare\nHollywood Squares\nJeopardy\nJeopardy 25th Anniversary Ed.\nJeopardy Jr.\nLion King'', The\nMarble Madness\nMarble Madness (PAL)\nNARC\nNightmare on Elm Street, A\nRC Pro-Am 2\nSolar Jetman\nSolar Jetman (PAL)\nSolstice\nSolstice (J)\nSuper Off Road\nTime Lord\nTime Lord (PAL)\nWheel of Fortune\nWheel of Fortune Family Edition\nWheel of Fortune W/ Vanna White\nWho Framed Roger Rabbit?\nWizards and Warriors\nWizards and Warriors (PAL)\nWizards and Warriors 2\nWizards and Warriors 3\nWorld Games\nWWF Wrestlemania\nWWF Wrestlemania Challenge');
INSERT INTO `reference` VALUES (346,51,'','Unused mapper');
INSERT INTO `reference` VALUES (347,52,'','MMC2 (Mapper 009)\n\nCompany:             Nintendo\nGames:               1 in NesCartDB\nComplexity:          ASIC\nBoards:              PNROM, PEEOROM\nPRG ROM capacity:    128K\nPRG ROM window:      8K + 24K fixed\nPRG RAM capacity:    8K (PC10 ver.)\nPRG RAM window:      Fixed\nCHR capacity:        128K\nCHR window:          4K + 4K (triggered)\nNametable mirroring: H or V,'' switchable\nBus conflicts:       No\nIRQ:                 No\nAudio:               No\niNES mappers:        009\n\nGames:\n\nMike Tyson''''s Punch-Out\nPunch-Out\nPunch-Out Shohinban''');
INSERT INTO `reference` VALUES (348,53,'','MMC4 (Mapper 010)\n\nCompany:             Nintendo\nGames:               3 in NesCartDB\nComplexity:          ASIC\nBoards:              FJROM, FKROM\nPRG ROM capacity:    256K\nPRG ROM window:      16K + 16K fixed\nPRG RAM capacity:    8K\nPRG RAM window:      8K\nCHR capacity:        128K\nCHR window:          4K + 4K (triggered)\nNametable mirroring: H or V, switchable\nBus conflicts:       No\nIRQ:                 No\nAudio:               No\niNES mappers:        010\n\nGames:\n\nFamicom Wars\nFire Emblem');
INSERT INTO `reference` VALUES (349,54,'','Color Dreams (Mapper 011)\n\nCompany:             Color Dreams/Wisdom Tree\nBoards:              COLORDREAMS\nPRG ROM capacity:    128K\nPRG ROM window:      32K\nPRG RAM capacity:    None\nCHR capacity:        32K\nCHR window:          8k\nNametable mirroring: Fixed H or V,'' controlled by solder pads\nBus conflicts:       Yes\nIRQ:                 No\nAudio:               No\niNES mappers:        011\n\nGames:\n\nAdventures of Captain Comic\nBaby Boomer\nBible Adventures\nCastle of Deceit\nCrystal Mines 2\nExodus\nKing of Kings\nMaster Chu and the Drunkard Hu\nMetal Fighter\nMission Cobra\nPesterminator\nRaid 2020\nSilent Assault\nSpiritual Warfare\nTagin'''' Dragon''');
INSERT INTO `reference` VALUES (350,55,'','REX DBZ 5 (Mapper 012)');
INSERT INTO `reference` VALUES (351,56,'','CPROM (Mapper 013)');
INSERT INTO `reference` VALUES (352,57,'','REX SL-1632 (Mapper 014)');
INSERT INTO `reference` VALUES (353,58,'','100-in-1 (Mapper 015)\n\nGames:\n\n100 In 1 - Contra Function 16\nCrazy Climber [hacked]\nMobile Suit Gundam Z (hacked)');
INSERT INTO `reference` VALUES (354,59,'','BANDAI 24C02 (Mapper 016)\n\nGames:\n\nAkuma Kun\nAkumajo Dracula 3 [Hacked]\nBlue Train Satsujin Jiken\nDatach Dragonball Z\nDragonball 2\nDragonball 3\nDragonball Z\nDragonball Z 2\nDragonball Z 3\nDragonball Z Gaiden\nFamicom Jump\nKureyon Shinchan\nMagical Taruruto-Kun\nMagical Taruruto-Kun 2\nSakigake Otoko Jyuku\nSD Gundam Knight Story\nSD Gundam Knight Story 2\nSD Gundam Knight Story 3');
INSERT INTO `reference` VALUES (355,60,'','FFE Rev. B (Mapper 017)\n\nGames:\n\nDragonball Z 2 [hacked]\nDragonball Z 3 [hacked]\nDynamite Batman 2 [Hacked]\nKaiketsu Yanchamaru Karakuri Land 2 [hacked]\nParodius [Hacked]\nSaiyuuki World 2 [Hacked]\nSpartan X2  [Hacked]\nWai Wai World (Hacked)');
INSERT INTO `reference` VALUES (356,61,'','JALECO SS880006 (Mapper 018)\n\nGames:\n\nJajamaru no Gekimaden\nJajamaru no Ginga Daisakusen\nLord of King,'' The\nMagic John\nMezase Top Pro\nMoeru Pro Baseball ''''90\nPizza Pop\nPlazma Ball\nTurupika Higemaru''');
INSERT INTO `reference` VALUES (357,62,'','Namcot 106 (Mapper 019)\n\nCompany:             Namco\nGames:               20 in NesCartDB\nComplexity:          ASIC\nBoards:              11xF0, 111F0S\nPRG ROM capacity:    512K\nPRG ROM window:      8Kx3 + 8K fixed\nPRG RAM capacity:    8K\nPRG RAM window:      8K\nCHR capacity:        256K\nCHR window:          1Kx8 (PT) + 1Kx4 (NT)\nNametable mirroring: arbitrary,'' up to 226 source nametables\nBus conflicts:       No\nIRQ:                 CPU cycle counter\nAudio:               Yes\niNES mappers:        019\n\nGames:\n\nDream Master\nFamily Circuit ''''91\nFamily Stadium ''''90\nFinal Lap\nHydlide 3\nJovei Quest\nMappy Kids\nMegami Tensei 2\nMindseeker\nNamco Classic\nRolling Thunder (J)\nSangokusi Chugen no Hasya\nSplatterhouse\nWagyan Land 2\nWagyan Land 3\nYoukai Douchuki''');
INSERT INTO `reference` VALUES (358,63,'','Unused mapper');
INSERT INTO `reference` VALUES (359,64,'','Konami VRC2/VRC4 A (Mapper 021)\n\nGames:\n\nGanbare Goemon Gaiden 2\nWai Wai World 2');
INSERT INTO `reference` VALUES (360,65,'','Konami VRC2/VRC4 B (Mapper 022)\n\nGames:\n\nTwinbee 3');
INSERT INTO `reference` VALUES (361,66,'','Konami VRC2/VRC4 C (Mapper 023)\n\nGames:\n\nBoku Dracula Kun\nContra (J)\nGetsufuu Maden\nJarinko Chie\nWai Wai World');
INSERT INTO `reference` VALUES (362,67,'','Konami VRC6 Rev. A (Mapper 024)\n\nCompany:             Konami\nGames:               3 in NesCartDB\nComplexity:          ASIC\nBoards:              351951, 351949A\nPRG ROM capacity:    256K\nPRG ROM window:      16K + 8K\nPRG RAM capacity:    8K\nPRG RAM window:      8K\nCHR capacity:        256K\nCHR window:          1K\nNametable mirroring: H, V, or 1, switchable\nBus conflicts:       No\nIRQ:                 Yes\nAudio:               Yes\niNES mappers:        024, 026\n\nGames:\n\nAkumajo Dracula 3');
INSERT INTO `reference` VALUES (363,68,'','Konami VRC2/VRC4 D (Mapper 025)\n\nGames:\n\nGanbare Goemon Gaiden\nGradius 2');
INSERT INTO `reference` VALUES (364,69,'','Konami VRC6 Rev. B (Mapper 026)\n\nCompany:             Konami\nGames:               3 in NesCartDB\nComplexity:          ASIC\nBoards:              351951, 351949A\nPRG ROM capacity:    256K\nPRG ROM window:      16K + 8K\nPRG RAM capacity:    8K\nPRG RAM window:      8K\nCHR capacity:        256K\nCHR window:          1K\nNametable mirroring: H, V, or 1, switchable\nBus conflicts:       No\nIRQ:                 Yes\nAudio:               Yes\niNES mappers:        024, 026\n\nGames:\n\nMouryou Senki Madara');
INSERT INTO `reference` VALUES (365,70,'','CC-21 MI HUN CHE (Mapper 027)');
INSERT INTO `reference` VALUES (366,71,'','Unused mapper');
INSERT INTO `reference` VALUES (367,72,'','RET-CUFROM (Mapper 029)');
INSERT INTO `reference` VALUES (368,73,'','UNROM 512 (Mapper 030)');
INSERT INTO `reference` VALUES (369,74,'','infiniteneslives-NSF (Mapper 031)');
INSERT INTO `reference` VALUES (370,75,'','IREM G-101 (Mapper 032)\n\nGames:\n\nAi Sensei no Oshiete Watashi no Hosi\nImage Fight (J)\nMeikyu Jima\nParman');
INSERT INTO `reference` VALUES (371,76,'','TC0190FMC/TC0350FMR (Mapper 033)\n\nGames:\n\nBakusyou Jinsei Gekijyou\nDon Doko Don\nDon Doko Don 2\nGolf Open\nInsector X\nMajor League');
INSERT INTO `reference` VALUES (372,77,'','IREM I-IM/BNROM (Mapper 034)\n\nGames:\n\n3D Worldrunner\nDeadly Towers\nDragonball [hacked]\nImpossible Mission 2\nMasyou\nTakahasi Meijin no Bug Hunny');
INSERT INTO `reference` VALUES (373,78,'','Wario Land 2 (Mapper 035)');
INSERT INTO `reference` VALUES (374,79,'','TXC Policeman (Mapper 036)');
INSERT INTO `reference` VALUES (375,80,'','PAL-ZZ SMB/TETRIS/NWC (Mapper 037)');
INSERT INTO `reference` VALUES (376,81,'','Bit Corp. (Mapper 038)\n\nCompany:             Bit Corp.\nGames:               1 in NesCartDB\nBoards:              UNL-PCI556\nPRG ROM capacity:    128K\nPRG ROM window:      32K\nPRG RAM capacity:    None\nCHR capacity:        32K\nCHR window:          8k\nNametable mirroring: V(hardwired)\nBus conflicts:       No\nIRQ:                 No\nAudio:               No\niNES mappers:        03');
INSERT INTO `reference` VALUES (377,82,'','Unused mapper');
INSERT INTO `reference` VALUES (378,83,'','SMB2j FDS (Mapper 040)');
INSERT INTO `reference` VALUES (379,84,'','CALTRON 6-in-1 (Mapper 041)');
INSERT INTO `reference` VALUES (380,85,'','BIO MIRACLE FDS (Mapper 042)');
INSERT INTO `reference` VALUES (381,86,'','FDS SMB2j LF36 (Mapper 043)');
INSERT INTO `reference` VALUES (382,87,'','MMC3 BMC PIRATE A (Mapper 044)');
INSERT INTO `reference` VALUES (383,88,'','MMC3 BMC PIRATE B (Mapper 045)');
INSERT INTO `reference` VALUES (384,89,'','RUMBLESTATION 15-in-1 (Mapper 046)');
INSERT INTO `reference` VALUES (385,90,'','NES-QJ SSVB/NWC (Mapper 047)');
INSERT INTO `reference` VALUES (386,91,'','TAITO TCxxx (Mapper 048)\n\nGames:\n\nSangokusi Chugen no Hasya 2 [Hacked]');
INSERT INTO `reference` VALUES (387,92,'','MMC3 BMC PIRATE C (Mapper 049)');
INSERT INTO `reference` VALUES (388,93,'','SMB2j FDS Rev. A (Mapper 050)');
INSERT INTO `reference` VALUES (389,94,'','11-in-1 BALL SERIES (Mapper 051)');
INSERT INTO `reference` VALUES (390,95,'','MMC3 BMC PIRATE D (Mapper 052)');
INSERT INTO `reference` VALUES (391,96,'','SUPERVISION 16-in-1 (Mapper 053)');
INSERT INTO `reference` VALUES (392,97,'','Unused mapper');
INSERT INTO `reference` VALUES (393,98,'','Unused mapper');
INSERT INTO `reference` VALUES (394,99,'','Unused mapper');
INSERT INTO `reference` VALUES (395,100,'','SIMBPLE BMC PIRATE A (Mapper 057)');
INSERT INTO `reference` VALUES (396,101,'','SIMBPLE BMC PIRATE B (Mapper 058)');
INSERT INTO `reference` VALUES (397,102,'','Unused mapper');
INSERT INTO `reference` VALUES (398,103,'','SIMBPLE BMC PIRATE C (Mapper 060)');
INSERT INTO `reference` VALUES (399,104,'','20-in-1 KAISER Rev. A (Mapper 061)');
INSERT INTO `reference` VALUES (400,105,'','700-in-1 (Mapper 062)');
INSERT INTO `reference` VALUES (401,106,'','Unused mapper');
INSERT INTO `reference` VALUES (402,107,'','TENGEN RAMBO1 (Mapper 064)\n\nCompany:             Tengen\nGames:               5 in NesCartDB\nComplexity:          ASIC\nBoards:              800032\nPRG ROM capacity:    256K\nPRG ROM window:      3x8K + 8K fixed\nPRG RAM capacity:    None\nCHR capacity:        256K\nCHR window:          1Kx8 or 2Kx2 + 1Kx4\nNametable mirroring: H or V, switchable\nBus conflicts:       No\nIRQ:                 Yes\nAudio:               No\niNES mappers:        064, 158\n\nGames:\n\nKlax\nShinobi');
INSERT INTO `reference` VALUES (403,108,'','IREM-H3001 (Mapper 065)\n\nGames:\n\nDaiku no Gensan 2\nKaiketsu Yanchamaru Karakuri Land 3');
INSERT INTO `reference` VALUES (404,109,'','MHROM (Mapper 066)\n\nCompany:             Nintendo, others\nBoards:              GNROM,MHROM\nPRG ROM capacity:    128KiB (512KiB oversize)\nPRG ROM window:      32KiB\nPRG RAM capacity:    None\nCHR capacity:        32KiB (128KiB oversize)\nCHR window:          8KiB\nNametable mirroring: Fixed H or V, controlled by solder pads\nBus conflicts:       Yes\nIRQ:                 No\nAudio:               No\niNES mappers:        066\n\nGames:\n\nBio Senshi Dan\nDragon Power\nDragonball\nFamily Block\nGumshoe\nSuper Mario Bros / Duck Hunt\nYoukai Club');
INSERT INTO `reference` VALUES (405,110,'','SUNSOFT-FZII (Mapper 067)');
INSERT INTO `reference` VALUES (406,111,'','Sunsoft Mapper #4 (Mapper 068)\n\nGames:\n\nAfterburner 2 (J)\nMaharaja\nNantteta Baseball');
INSERT INTO `reference` VALUES (407,112,'','SUNSOFT-5/FME-7 (Mapper 069)\n\nCompany:             Sunsoft\nGames:               9 in NesCartDB\nComplexity:          ASIC\nBoards:              JLROM, JSROM,NES-BTR, others\nPRG ROM capacity:    512K (FME-7)256K (5A/5B)\nPRG ROM window:      8Kx4 + 8K fixed\nPRG RAM capacity:    512K (FME-7)\nPRG RAM window:      8K\nCHR capacity:        256K\nCHR window:          1Kx8\nNametable mirroring: H, V, or 1, switchable\nBus conflicts:       No\nIRQ:                 CPU cycle counter\nAudio:               5B only\niNES mappers:        069\n\nGames:\n\nBatman (J)\nBatman - Return of the Joker\nDodge Danpei 2\nDynamite Batman 2\nGimmick!\nHebereke');
INSERT INTO `reference` VALUES (408,113,'','BA KAMEN DISCRETE (Mapper 070)\n\nGames:\n\nGegege no Kitarou 2\nKamen Rider Club');
INSERT INTO `reference` VALUES (409,114,'','CAMERICA BF9093 (Mapper 071)\n\nGames:\n\nBee 52\nBig Nose Freaks Out\nDizzy The Adventurer\nFantastic Adventures of Dizzy, The [Aladdin vers.]\nFirehawk\nLinus Spacehead\nLinus Spacehead [Aladdin Ver.]\nMicro Machines\nMicro Machines [Aladdin Ver.]\nQuattro Adventure\nQuattro Sports\nUltimate Stuntman');
INSERT INTO `reference` VALUES (410,115,'','JALECO JF-17 (Mapper 072)');
INSERT INTO `reference` VALUES (411,116,'','KONAMI VRC3 (Mapper 073)');
INSERT INTO `reference` VALUES (412,117,'','TW MMC3+VRAM Rev. A (Mapper 074)');
INSERT INTO `reference` VALUES (413,118,'','KONAMI VRC1 (Mapper 075)');
INSERT INTO `reference` VALUES (414,119,'','NAMCOT 108 Rev. A (Mapper 076)');
INSERT INTO `reference` VALUES (415,120,'','IREM LROG017 (Mapper 077)');
INSERT INTO `reference` VALUES (416,121,'','Irem 74HC161/32 (Mapper 078)\n\nGames:\n\nHoly Diver');
INSERT INTO `reference` VALUES (417,122,'','AVE/C&E/TXC BOARD (Mapper 079)\n\nCompany:             American Video Entertainment\nBoards:              NINA-03, NINA-06\nPRG ROM capacity:    64K\nPRG ROM window:      32K\nPRG RAM capacity:    None\nCHR capacity:        64K\nCHR window:          8k\nNametable mirroring: Fixed H or V, controlled by solder pads\nBus conflicts:       No\nIRQ:                 No\nAudio:               No\niNES mappers:        079\n\nGames:\n\nDouble Strike\nDudes With Attitudes\nF15 City War\nKrazy Kreatures\nTrolls on Treasure Island\nUltimate League Soccer\nVenice Beach Volleyball');
INSERT INTO `reference` VALUES (418,123,'','TAITO X1-005 Rev. A (Mapper 080)\n\nGames:\n\nTaito Grand Prix');
INSERT INTO `reference` VALUES (419,124,'','Unused mapper');
INSERT INTO `reference` VALUES (420,125,'','TAITO X1-017 (Mapper 082)\n\nGames:\n\nKyuukyoku Stadium\nKyuukyoko Harikiri Stadium\nKyuukyoku Harikiri Stadium 3\nSD Keiji Blader');
INSERT INTO `reference` VALUES (421,126,'','YOKO VRC Rev. B (Mapper 083)\n\nGames:\n\nGarou Densetsu Special');
INSERT INTO `reference` VALUES (422,127,'','Unused mapper');
INSERT INTO `reference` VALUES (423,128,'','KONAMI VRC7 (Mapper 085)\n\nCompany:             Konami\nGames:               2 in NesCartDB\nComplexity:          ASIC\nBoards:              352402, 353429\nPRG ROM capacity:    512K\nPRG ROM window:      8K\nPRG RAM capacity:    8K\nPRG RAM window:      8K\nCHR capacity:        256K\nCHR window:          1K\nNametable mirroring: H, V, or 1, switchable\nBus conflicts:       No\nIRQ:                 Yes\nAudio:               VRC7a only\niNES mappers:        085\n\nGames:\n\nLagrange Point');
INSERT INTO `reference` VALUES (424,129,'','JALECO JF-13 (Mapper 086)');
INSERT INTO `reference` VALUES (425,130,'','74*139/74 DISCRETE (Mapper 087)');
INSERT INTO `reference` VALUES (426,131,'','NAMCO 3433 (Mapper 088)\n\nGames:\n\nDragon Spirit (J)');
INSERT INTO `reference` VALUES (427,132,'','SUNSOFT-3 (Mapper 089)');
INSERT INTO `reference` VALUES (428,133,'','HUMMER/JY BOARD (Mapper 090)\n\nGames:\n\nMortal Kombat 3\nTekken 2');
INSERT INTO `reference` VALUES (429,134,'','EARLY HUMMER/JY BOARD (Mapper 091)\n\nGames:\n\nStreet Fighter 3');
INSERT INTO `reference` VALUES (430,135,'','JALECO JF-19 (Mapper 092)');
INSERT INTO `reference` VALUES (431,136,'','SUNSOFT-3R (Mapper 093)');
INSERT INTO `reference` VALUES (432,137,'','HVC-UN1ROM (Mapper 094)\n\nPRG ROM capacity:    128K\nPRG ROM bank size:   16K\nPRG RAM capacity:    None\nCHR capacity:        8K\nCHR bank size:       Not bankswitched\nNametable mirroring: Solder pads select vertical or horizontal mirroring\nBus conflicts:       Yes\n\nGames:\n\nSenjou no Ookami');
INSERT INTO `reference` VALUES (433,138,'','NAMCOT 108 Rev. B (Mapper 095)\n\nGames:\n\nDragon Buster');
INSERT INTO `reference` VALUES (434,139,'','BANDAI OEKAKIDS (Mapper 096)');
INSERT INTO `reference` VALUES (435,140,'','IREM TAM-S1 (Mapper 097)\n\nGames:\n\nCrazy Climber');
INSERT INTO `reference` VALUES (436,141,'','Unused mapper');
INSERT INTO `reference` VALUES (437,142,'','VS Uni/Dual- system (Mapper 099)\n\nGames:\n\nVs. Castlevania\nVs. Ice Climber\nVs. Super Mario Bros');
INSERT INTO `reference` VALUES (438,143,'','Unused mapper');
INSERT INTO `reference` VALUES (439,144,'','Unused mapper');
INSERT INTO `reference` VALUES (440,145,'','Unused mapper');
INSERT INTO `reference` VALUES (441,146,'','FDS DOKIDOKI FULL (Mapper 103)');
INSERT INTO `reference` VALUES (442,147,'','Unused mapper');
INSERT INTO `reference` VALUES (443,148,'','NES-EVENT NWC1990 (Mapper 105)');
INSERT INTO `reference` VALUES (444,149,'','SMB3 PIRATE A (Mapper 106)');
INSERT INTO `reference` VALUES (445,150,'','MAGIC CORP A (Mapper 107)');
INSERT INTO `reference` VALUES (446,151,'','FDS UNROM BOARD (Mapper 108)');
INSERT INTO `reference` VALUES (447,152,'','Unused mapper');
INSERT INTO `reference` VALUES (448,153,'','Unused mapper');
INSERT INTO `reference` VALUES (449,154,'','Unused mapper');
INSERT INTO `reference` VALUES (450,155,'','ASDER/NTDEC BOARD (Mapper 112)');
INSERT INTO `reference` VALUES (451,156,'','HACKER/SACHEN BOARD (Mapper 113)\n\nCompany:             unknown\nBoards:              unknown\nPRG ROM capacity:    256K\nPRG ROM window:      32K\nPRG RAM capacity:    None\nCHR capacity:        128K\nCHR window:          8k\nNametable mirroring: H or V, controlled by mapper\nBus conflicts:       No\nIRQ:                 No\nAudio:               No\niNES mappers:        11');
INSERT INTO `reference` VALUES (452,157,'','MMC3 SG PROT. A (Mapper 114)');
INSERT INTO `reference` VALUES (453,158,'','MMC3 PIRATE A (Mapper 115)');
INSERT INTO `reference` VALUES (454,159,'','MMC1/MMC3/VRC PIRATE (Mapper 116)');
INSERT INTO `reference` VALUES (455,160,'','FUTURE MEDIA BOARD (Mapper 117)');
INSERT INTO `reference` VALUES (456,161,'','TSKROM (Mapper 118)');
INSERT INTO `reference` VALUES (457,162,'','NES-TQROM (Mapper 119)\n\nGames:\n\nHigh Speed\nHigh Speed (PAL)\nPinbot\nPinbot (PAL)');
INSERT INTO `reference` VALUES (458,163,'','FDS TOBIDASE (Mapper 120)');
INSERT INTO `reference` VALUES (459,164,'','MMC3 PIRATE PROT. A (Mapper 121)');
INSERT INTO `reference` VALUES (460,165,'','Unused mapper');
INSERT INTO `reference` VALUES (461,166,'','MMC3 PIRATE H2288 (Mapper 123)');
INSERT INTO `reference` VALUES (462,167,'','Unused mapper');
INSERT INTO `reference` VALUES (463,168,'','FDS LH32 (Mapper 125)');
INSERT INTO `reference` VALUES (464,169,'','Unused mapper');
INSERT INTO `reference` VALUES (465,170,'','Unused mapper');
INSERT INTO `reference` VALUES (466,171,'','Unused mapper');
INSERT INTO `reference` VALUES (467,172,'','Unused mapper');
INSERT INTO `reference` VALUES (468,173,'','Unused mapper');
INSERT INTO `reference` VALUES (469,174,'','Unused mapper');
INSERT INTO `reference` VALUES (470,175,'','TXC/MGENIUS 22111 (Mapper 132)');
INSERT INTO `reference` VALUES (471,176,'','SA72008 (Mapper 133)');
INSERT INTO `reference` VALUES (472,177,'','MMC3 BMC PIRATE (Mapper 134)');
INSERT INTO `reference` VALUES (473,178,'','Unused mapper');
INSERT INTO `reference` VALUES (474,179,'','TCU02 (Mapper 136)');
INSERT INTO `reference` VALUES (475,180,'','S8259D (Mapper 137)');
INSERT INTO `reference` VALUES (476,181,'','S8259B (Mapper 138)');
INSERT INTO `reference` VALUES (477,182,'','S8259C (Mapper 139)');
INSERT INTO `reference` VALUES (478,183,'','JALECO JF-11/14 (Mapper 140)');
INSERT INTO `reference` VALUES (479,184,'','S8259A (Mapper 141)');
INSERT INTO `reference` VALUES (480,185,'','UNLKS7032 (Mapper 142)');
INSERT INTO `reference` VALUES (481,186,'','TCA01 (Mapper 143)');
INSERT INTO `reference` VALUES (482,187,'','AGCI 50282 (Mapper 144)');
INSERT INTO `reference` VALUES (483,188,'','SA72007 (Mapper 145)');
INSERT INTO `reference` VALUES (484,189,'','SA0161M (Mapper 146)');
INSERT INTO `reference` VALUES (485,190,'','TCU01 (Mapper 147)');
INSERT INTO `reference` VALUES (486,191,'','SA0037 (Mapper 148)');
INSERT INTO `reference` VALUES (487,192,'','SA0036 (Mapper 149)');
INSERT INTO `reference` VALUES (488,193,'','S74LS374N (Mapper 150)');
INSERT INTO `reference` VALUES (489,194,'','Unused mapper');
INSERT INTO `reference` VALUES (490,195,'','Unused mapper');
INSERT INTO `reference` VALUES (491,196,'','BANDAI SRAM (Mapper 153)');
INSERT INTO `reference` VALUES (492,197,'','Unused mapper');
INSERT INTO `reference` VALUES (493,198,'','Unused mapper');
INSERT INTO `reference` VALUES (494,199,'','Unused mapper');
INSERT INTO `reference` VALUES (495,200,'','BANDAI BARCODE (Mapper 157)');
INSERT INTO `reference` VALUES (496,201,'','Unused mapper');
INSERT INTO `reference` VALUES (497,202,'','BANDAI 24C01 (Mapper 159)');
INSERT INTO `reference` VALUES (498,203,'','SA009 (Mapper 160)');
INSERT INTO `reference` VALUES (499,204,'','Unused mapper');
INSERT INTO `reference` VALUES (500,205,'','Unused mapper');
INSERT INTO `reference` VALUES (501,206,'','Unused mapper');
INSERT INTO `reference` VALUES (502,207,'','Unused mapper');
INSERT INTO `reference` VALUES (503,208,'','Unused mapper');
INSERT INTO `reference` VALUES (504,209,'','SUBOR Rev. A (Mapper 166)');
INSERT INTO `reference` VALUES (505,210,'','SUBOR Rev. B (Mapper 167)');
INSERT INTO `reference` VALUES (506,211,'','Unused mapper');
INSERT INTO `reference` VALUES (507,212,'','Unused mapper');
INSERT INTO `reference` VALUES (508,213,'','Unused mapper');
INSERT INTO `reference` VALUES (509,214,'','Unused mapper');
INSERT INTO `reference` VALUES (510,215,'','Unused mapper');
INSERT INTO `reference` VALUES (511,216,'','Unused mapper');
INSERT INTO `reference` VALUES (512,217,'','Unused mapper');
INSERT INTO `reference` VALUES (513,218,'','Unused mapper');
INSERT INTO `reference` VALUES (514,219,'','BMCFK23C (Mapper 176)');
INSERT INTO `reference` VALUES (515,220,'','Unused mapper');
INSERT INTO `reference` VALUES (516,221,'','Unused mapper');
INSERT INTO `reference` VALUES (517,222,'','Unused mapper');
INSERT INTO `reference` VALUES (518,223,'','UNROM (Mapper 180)\n\nPRG ROM capacity:    128K\nPRG ROM bank size:   16K\nPRG RAM capacity:    None\nCHR capacity:        8K\nCHR bank size:       Not bankswitched\nNametable mirroring: Solder pads select vertical or horizontal mirroring\nBus conflicts:       Yes\n\nGames:\n\nCrazy Climber');
INSERT INTO `reference` VALUES (519,224,'','Unused mapper');
INSERT INTO `reference` VALUES (520,225,'','Unused mapper');
INSERT INTO `reference` VALUES (521,226,'','Unused mapper');
INSERT INTO `reference` VALUES (522,227,'','Unused mapper');
INSERT INTO `reference` VALUES (523,228,'','Unused mapper');
INSERT INTO `reference` VALUES (524,229,'','Unused mapper');
INSERT INTO `reference` VALUES (525,230,'','Unused mapper');
INSERT INTO `reference` VALUES (526,231,'','Unused mapper');
INSERT INTO `reference` VALUES (527,232,'','Unused mapper');
INSERT INTO `reference` VALUES (528,233,'','Unused mapper');
INSERT INTO `reference` VALUES (529,234,'','Unused mapper');
INSERT INTO `reference` VALUES (530,235,'','TW MMC3+VRAM Rev. B (Mapper 192)');
INSERT INTO `reference` VALUES (531,236,'','NTDEC TC-112 (Mapper 193)');
INSERT INTO `reference` VALUES (532,237,'','TW MMC3+VRAM Rev. C (Mapper 194)');
INSERT INTO `reference` VALUES (533,238,'','TW MMC3+VRAM Rev. D (Mapper 195)');
INSERT INTO `reference` VALUES (534,239,'','Unused mapper');
INSERT INTO `reference` VALUES (535,240,'','Unused mapper');
INSERT INTO `reference` VALUES (536,241,'','TW MMC3+VRAM Rev. E (Mapper 198)');
INSERT INTO `reference` VALUES (537,242,'','Unused mapper');
INSERT INTO `reference` VALUES (538,243,'','Unused mapper');
INSERT INTO `reference` VALUES (539,244,'','Unused mapper');
INSERT INTO `reference` VALUES (540,245,'','Unused mapper');
INSERT INTO `reference` VALUES (541,246,'','Unused mapper');
INSERT INTO `reference` VALUES (542,247,'','Unused mapper');
INSERT INTO `reference` VALUES (543,248,'','Unused mapper');
INSERT INTO `reference` VALUES (544,249,'','NAMCOT 108 Rev. C (Mapper 206)\n\nCompany:             Namco, Tengen, others\nGames:               39 in NesCartDB\nComplexity:          ASIC\nBoards:              34xx, DxROM\nPRG ROM capacity:    128K\nPRG ROM window:      8K + 8K + 16K fixed\nPRG RAM capacity:    None\nCHR capacity:        64K\nCHR window:          2Kx2 + 1Kx4\nNametable mirroring: Fixed H/V, or 4\nBus conflicts:       No\nIRQ:                 No\nAudio:               No\niNES mappers:        206,76,88,154, 9');
INSERT INTO `reference` VALUES (545,250,'','TAITO X1-005 Rev. B (Mapper 207)');
INSERT INTO `reference` VALUES (546,251,'','Unused mapper');
INSERT INTO `reference` VALUES (547,252,'','Unused mapper');
INSERT INTO `reference` VALUES (548,253,'','Unused mapper');
INSERT INTO `reference` VALUES (549,254,'','Unused mapper');
INSERT INTO `reference` VALUES (550,255,'','Unused mapper');
INSERT INTO `reference` VALUES (551,256,'','Unused mapper');
INSERT INTO `reference` VALUES (552,257,'','Unused mapper');
INSERT INTO `reference` VALUES (553,258,'','Unused mapper');
INSERT INTO `reference` VALUES (554,259,'','Unused mapper');
INSERT INTO `reference` VALUES (555,260,'','Unused mapper');
INSERT INTO `reference` VALUES (556,261,'','Unused mapper');
INSERT INTO `reference` VALUES (557,262,'','UNLA9746 (Mapper 219)');
INSERT INTO `reference` VALUES (558,263,'','Debug Mapper (Mapper 220)');
INSERT INTO `reference` VALUES (559,264,'','UNLN625092 (Mapper 221)');
INSERT INTO `reference` VALUES (560,265,'','Unused mapper');
INSERT INTO `reference` VALUES (561,266,'','Unused mapper');
INSERT INTO `reference` VALUES (562,267,'','Unused mapper');
INSERT INTO `reference` VALUES (563,268,'','Unused mapper');
INSERT INTO `reference` VALUES (564,269,'','BMC 22+20-in-1 (Mapper 226)');
INSERT INTO `reference` VALUES (565,270,'','Unused mapper');
INSERT INTO `reference` VALUES (566,271,'','Unused mapper');
INSERT INTO `reference` VALUES (567,272,'','Unused mapper');
INSERT INTO `reference` VALUES (568,273,'','BMC Contra+22-in-1 (Mapper 230)');
INSERT INTO `reference` VALUES (569,274,'','Unused mapper');
INSERT INTO `reference` VALUES (570,275,'','BMC QUATTRO (Mapper 232)');
INSERT INTO `reference` VALUES (571,276,'','BMC 22+20-in-1 RST (Mapper 233)');
INSERT INTO `reference` VALUES (572,277,'','BMC MAXI (Mapper 234)');
INSERT INTO `reference` VALUES (573,278,'','Unused mapper');
INSERT INTO `reference` VALUES (574,279,'','Unused mapper');
INSERT INTO `reference` VALUES (575,280,'','Unused mapper');
INSERT INTO `reference` VALUES (576,281,'','UNL6035052 (Mapper 238)');
INSERT INTO `reference` VALUES (577,282,'','Unused mapper');
INSERT INTO `reference` VALUES (578,283,'','Unused mapper');
INSERT INTO `reference` VALUES (579,284,'','Unused mapper');
INSERT INTO `reference` VALUES (580,285,'','Unused mapper');
INSERT INTO `reference` VALUES (581,286,'','S74LS374NA (Mapper 243)');
INSERT INTO `reference` VALUES (582,287,'','DECATHLON (Mapper 244)');
INSERT INTO `reference` VALUES (583,288,'','Unused mapper');
INSERT INTO `reference` VALUES (584,289,'','FONG SHEN BANG (Mapper 246)');
INSERT INTO `reference` VALUES (585,290,'','Unused mapper');
INSERT INTO `reference` VALUES (586,291,'','Unused mapper');
INSERT INTO `reference` VALUES (587,292,'','Unused mapper');
INSERT INTO `reference` VALUES (588,293,'','Unused mapper');
INSERT INTO `reference` VALUES (589,294,'','Unused mapper');
INSERT INTO `reference` VALUES (590,295,'','SAN GUO ZHI PIRATE (Mapper 252)');
INSERT INTO `reference` VALUES (591,296,'','DRAGON BALL PIRATE (Mapper 253)');
INSERT INTO `reference` VALUES (592,297,'','Unused mapper');
INSERT INTO `reference` VALUES (593,298,'','Unused mapper');
CREATE TABLE users (
	id INTEGER NOT NULL,
	name VARCHAR(128),
    username VARCHAR(128),
	email VARCHAR(128),
	password VARCHAR(128),
	date_created DATETIME,
	date_login DATETIME,
	login_token VARCHAR(128),
    reset_token VARCHAR(128),
    date_reset DATETIME,
    reset_id VARCHAR(128),
	PRIMARY KEY (id)
);
INSERT INTO `users` VALUES (1,'Kevin Selwyn','kevinselwyn','kevinselwyn@gmail.com','1a1dc91c907325c69271ddf0c944bc72','2017-03-14 10:29:03.225150','2017-03-17 10:04:56.231847',NULL,NULL,NULL,NULL);
COMMIT;
