site_name: Nessemble
copyright: © 2017 Kevin Selwyn
pages:
    - Home: index.md
    - Installation: installation.md
    - Building: building.md
    - Usage: usage.md
    - Syntax: syntax.md
    - Playground: playground.md
    - Disassembling: disassembling.md
    - Simulating: simulating.md
    - Packages: packages.md
    - Registry: registry.md
    - Extending: extending.md
    - Translating: translating.md
    - Licensing: licensing.md
    - Contributing: contributing.md
theme: readthedocs
theme_dir: custom_theme
docs_dir: pages
dev_addr: 0.0.0.0:9090
extra_css:
    - css/custom.css
    - css/nessemble.css
    - css/registry.css
    - css/bootstrap-modal.css
extra_javascript:
    - js/bootstrap-modal.js
    - js/nessemble.min.js
    - js/nessemble-custom.js
    - js/registry.js
